"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager event API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/event/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmp0h4wws1e.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AuditEventType(Enum):
    historic_action = "historic_action"
    inspection_passed = "inspection_passed"
    inspection_failed = "inspection_failed"
    inspection_unable_to_carry_out = "inspection_unable_to_carry_out"
    inspection_further_required = "inspection_further_required"
    inspection_withdraw_defect = "inspection_withdraw_defect"
    inspection_agreed_site_compliance = "inspection_agreed_site_compliance"
    activity_submitted = "activity_submitted"
    activity_edited = "activity_edited"
    activity_cancelled = "activity_cancelled"
    fpn_submitted = "fpn_submitted"
    fpn_accepted = "fpn_accepted"
    fpn_paid = "fpn_paid"
    fpn_disputed = "fpn_disputed"
    fpn_withdrawn = "fpn_withdrawn"
    permit_granted = "permit_granted"
    permit_refused = "permit_refused"
    permit_cancelled = "permit_cancelled"
    permit_revoked = "permit_revoked"
    permit_deemed = "permit_deemed"
    paa_granted = "paa_granted"
    paa_refused = "paa_refused"
    paa_cancelled = "paa_cancelled"
    paa_revoked = "paa_revoked"
    alteration_submitted = "alteration_submitted"
    alteration_refused = "alteration_refused"
    alteration_granted = "alteration_granted"
    alteration_granted_with_duration_challenge = (
        "alteration_granted_with_duration_challenge"
    )
    alteration_deemed = "alteration_deemed"
    alteration_cancelled = "alteration_cancelled"
    lane_rental_assessed = "lane_rental_assessed"
    reinstatement_submitted = "reinstatement_submitted"
    file_uploaded = "file_uploaded"
    comment_submitted = "comment_submitted"
    work_start_logged = "work_start_logged"
    work_stop_logged = "work_stop_logged"
    work_start_reverted = "work_start_reverted"
    work_stop_reverted = "work_stop_reverted"
    forward_plan_submitted = "forward_plan_submitted"
    forward_plan_cancelled = "forward_plan_cancelled"
    user_removed = "user_removed"
    user_invited = "user_invited"
    inspection_units_logged = "inspection_units_logged"
    permit_submitted = "permit_submitted"
    paa_submitted = "paa_submitted"
    forward_plan_edited = "forward_plan_edited"
    permit_discount_updated = "permit_discount_updated"
    paa_discount_updated = "paa_discount_updated"
    paa_deemed = "paa_deemed"
    organisation_contract_added = "organisation_contract_added"
    organisation_contract_removed = "organisation_contract_removed"
    organisation_updated = "organisation_updated"
    workstream_created = "workstream_created"
    workstream_updated = "workstream_updated"
    inspection_works_stopped = "inspection_works_stopped"
    inspection_works_stopped_apparatus_remaining = (
        "inspection_works_stopped_apparatus_remaining"
    )
    inspection_works_in_progress = "inspection_works_in_progress"
    inspection_works_in_progress_no_carriageway_incursion = (
        "inspection_works_in_progress_no_carriageway_incursion"
    )
    inspection_non_compliant_with_conditions = (
        "inspection_non_compliant_with_conditions"
    )
    permit_modification_request = "permit_modification_request"
    scheduled_inspection_cancelled = "scheduled_inspection_cancelled"
    scheduled_inspection_created = "scheduled_inspection_created"
    alteration_applied_auto = "alteration_applied_auto"
    section_81_submitted = "section_81_submitted"
    final_reinstatement_updated = "final_reinstatement_updated"
    section_81_acknowledged = "section_81_acknowledged"
    section_81_accepted = "section_81_accepted"
    section_81_accepted_fixed = "section_81_accepted_fixed"
    section_81_rejected = "section_81_rejected"
    section_81_resolved_by_ha = "section_81_resolved_by_ha"
    section_81_cancelled = "section_81_cancelled"
    user_roles_updated = "user_roles_updated"
    support_desk_action = "support_desk_action"
    user_name_updated = "user_name_updated"
    permit_hs2_acknowledged = "permit_hs2_acknowledged"
    geographical_area_created = "geographical_area_created"
    geographical_area_updated = "geographical_area_updated"
    workstream_access_updated = "workstream_access_updated"
    planned_works_record_created = "planned_works_record_created"
    in_progress_works_record_created = "in_progress_works_record_created"
    historic_works_record_created = "historic_works_record_created"
    non_notifiable_works_record_created = "non_notifiable_works_record_created"
    section_81_works_record_created = "section_81_works_record_created"
    unattributable_works_record_created = "unattributable_works_record_created"
    upcoming_event = "upcoming_event"
    sample_inspection_target_created = "sample_inspection_target_created"
    sample_inspection_target_updated = "sample_inspection_target_updated"
    sample_inspection_created = "sample_inspection_created"
    sample_inspection_completed = "sample_inspection_completed"
    sample_inspection_removed = "sample_inspection_removed"
    sample_inspection_expired = "sample_inspection_expired"
    internal_comment_submitted = "internal_comment_submitted"
    comment_read = "comment_read"
    excavation_carried_out_updated = "excavation_carried_out_updated"
    sample_inspection_target_closed = "sample_inspection_target_closed"
    section_81_linked_to_permit = "section_81_linked_to_permit"
    section_81_unlinked_from_permit = "section_81_unlinked_from_permit"
    section_81_reassigned = "section_81_reassigned"
    permit_granted_with_duration_challenge = "permit_granted_with_duration_challenge"
    inspection_withdrawn = "inspection_withdrawn"
    section_74_warning_issued = "section_74_warning_issued"
    section_74_warning_acknowledged = "section_74_warning_acknowledged"
    section_74_site_visited_and_rectified = "section_74_site_visited_and_rectified"
    section_74_charges_ended = "section_74_charges_ended"
    section_74_warning_disputed = "section_74_warning_disputed"
    section_74_withdrawn = "section_74_withdrawn"
    section_74_draft_invoice_issued = "section_74_draft_invoice_issued"
    section_74_resolved = "section_74_resolved"
    section_74_draft_invoice_acknowledged = "section_74_draft_invoice_acknowledged"
    section_74_charge_under_review = "section_74_charge_under_review"
    section_74_charge_agreed = "section_74_charge_agreed"
    alteration_duration_challenge_accepted = "alteration_duration_challenge_accepted"
    alteration_duration_challenge_not_accepted = (
        "alteration_duration_challenge_not_accepted"
    )
    alteration_duration_challenge_non_acceptance_response = (
        "alteration_duration_challenge_non_acceptance_response"
    )
    permit_duration_challenge_accepted = "permit_duration_challenge_accepted"
    permit_duration_challenge_not_accepted = "permit_duration_challenge_not_accepted"
    permit_duration_challenge_non_acceptance_response = (
        "permit_duration_challenge_non_acceptance_response"
    )
    section_58_created = "section_58_created"
    section_58_progressed = "section_58_progressed"
    section_58_cancelled = "section_58_cancelled"
    section_58_closed = "section_58_closed"
    reinstatement_deleted = "reinstatement_deleted"
    site_deleted = "site_deleted"
    inspection_deleted = "inspection_deleted"
    site_subsumed = "site_subsumed"
    fpn_deleted = "fpn_deleted"
    current_traffic_management_type_updated = "current_traffic_management_type_updated"
    ancillary_info_added = "ancillary_info_added"
    ancillary_info_removed = "ancillary_info_removed"
    sample_inspection_issued = "sample_inspection_issued"
    inspection_outcome_accepted = "inspection_outcome_accepted"
    inspection_outcome_disputed = "inspection_outcome_disputed"
    inspection_outcome_promoter_accepts_failed_inspection = (
        "inspection_outcome_promoter_accepts_failed_inspection"
    )
    sample_inspection_target_deleted = "sample_inspection_target_deleted"
    sample_inspection_quarter_started = "sample_inspection_quarter_started"
    sample_inspection_quarter_ended = "sample_inspection_quarter_ended"
    fee_matrix_updated = "fee_matrix_updated"
    organisation_fpn_details_updated = "organisation_fpn_details_updated"
    inspection_auto_accepted = "inspection_auto_accepted"
    sample_inspection_quarter_end_reverted = "sample_inspection_quarter_end_reverted"
    private_street_notice_issued = "private_street_notice_issued"
    private_street_notice_cancelled = "private_street_notice_cancelled"
    non_compliance_issued = "non_compliance_issued"
    non_compliance_withdrawn = "non_compliance_withdrawn"
    non_compliance_resolved = "non_compliance_resolved"
    inspection_linked_to_non_compliance = "inspection_linked_to_non_compliance"
    permit_linked_to_non_compliance = "permit_linked_to_non_compliance"
    inspection_outcome_joint_site_meeting_needed = (
        "inspection_outcome_joint_site_meeting_needed"
    )
    inspection_outcome_reviewing_dispute = "inspection_outcome_reviewing_dispute"
    inspection_outcome_no_agreement = "inspection_outcome_no_agreement"
    non_compliance_works_completed_and_passed = (
        "non_compliance_works_completed_and_passed"
    )
    non_compliance_joint_site_meeting_suggested = (
        "non_compliance_joint_site_meeting_suggested"
    )
    non_compliance_will_attend_joint_site_meeting = (
        "non_compliance_will_attend_joint_site_meeting"
    )
    non_compliance_works_complete_ready_for_inspection = (
        "non_compliance_works_complete_ready_for_inspection"
    )
    non_compliance_joint_site_meeting_not_needed = (
        "non_compliance_joint_site_meeting_not_needed"
    )
    event_subscription_created = "event_subscription_created"
    event_subscription_removed = "event_subscription_removed"
    material_classification_submitted = "material_classification_submitted"
    non_compliance_accept_suggestion = "non_compliance_accept_suggestion"
    permit_under_assessment = "permit_under_assessment"
    alteration_revoked = "alteration_revoked"
    change_request_submitted = "change_request_submitted"
    change_request_refused = "change_request_refused"
    change_request_granted = "change_request_granted"
    change_request_granted_with_duration_challenge = (
        "change_request_granted_with_duration_challenge"
    )
    change_request_deemed = "change_request_deemed"
    change_request_cancelled = "change_request_cancelled"
    change_request_applied_auto = "change_request_applied_auto"
    change_request_duration_challenge_accepted = (
        "change_request_duration_challenge_accepted"
    )
    change_request_duration_challenge_not_accepted = (
        "change_request_duration_challenge_not_accepted"
    )
    change_request_duration_challenge_non_acceptance_response = (
        "change_request_duration_challenge_non_acceptance_response"
    )
    change_request_revoked = "change_request_revoked"


class AuditObjectTypeResponse(Enum):
    permit = "permit"
    reinstatement = "reinstatement"
    inspection = "inspection"
    fpn = "fpn"
    paa = "paa"
    workstream = "workstream"
    work = "work"
    organisation = "organisation"
    activity = "activity"
    forward_plan = "forward_plan"
    comment = "comment"
    scheduled_inspection = "scheduled_inspection"
    section_81 = "section_81"
    user = "user"
    geographical_area = "geographical_area"
    change_request = "change_request"
    application = "application"
    sample_inspection = "sample_inspection"
    section_74 = "section_74"
    section_58 = "section_58"
    site = "site"
    sample_inspection_target = "sample_inspection_target"
    fee_matrix = "fee_matrix"
    non_compliance = "non_compliance"
    private_street = "private_street"
    event_subscription = "event_subscription"
    material_classification = "material_classification"
    upcoming_enum = "upcoming_enum"


class WorkUpdateSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    update_date_time: AwareDatetime
    update_id: float
    event_type: AuditEventType
    event_type_string: str
    object_type: AuditObjectTypeResponse
    object_type_string: str
    parent_object_reference_number: str | None = None
    object_reference_number: str | None = None


class WorkUpdateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[WorkUpdateSummaryResponse]
    next_update: float | None = None


class WorkCategoryResponse(Enum):
    minor = "minor"
    standard = "standard"
    major = "major"
    immediate_urgent = "immediate_urgent"
    immediate_emergency = "immediate_emergency"
    paa = "paa"
    hs2_highway = "hs2_highway"
    upcoming_enum = "upcoming_enum"


class TrafficManagementTypeResponse(Enum):
    road_closure = "road_closure"
    contra_flow = "contra_flow"
    lane_closure = "lane_closure"
    multi_way_signals = "multi_way_signals"
    two_way_signals = "two_way_signals"
    convoy_workings = "convoy_workings"
    stop_go_boards = "stop_go_boards"
    priority_working = "priority_working"
    give_and_take = "give_and_take"
    some_carriageway_incursion = "some_carriageway_incursion"
    no_carriageway_incursion = "no_carriageway_incursion"
    upcoming_enum = "upcoming_enum"


class AssessmentStatusResponse(Enum):
    granted = "granted"
    granted_auto = "granted_auto"
    refused = "refused"
    refused_auto = "refused_auto"
    permit_modification_request = "permit_modification_request"
    revoked = "revoked"
    upcoming_enum = "upcoming_enum"


class PermitStatusResponse(Enum):
    submitted = "submitted"
    granted = "granted"
    permit_modification_request = "permit_modification_request"
    refused = "refused"
    closed = "closed"
    cancelled = "cancelled"
    revoked = "revoked"
    progressed = "progressed"
    upcoming_enum = "upcoming_enum"


class WorkStatusResponse(Enum):
    planned = "planned"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"
    unattributable = "unattributable"
    historical = "historical"
    non_notifiable = "non_notifiable"
    section_81 = "section_81"
    upcoming_enum = "upcoming_enum"


class PermitConditionTypeResponse(Enum):
    NCT01a = "NCT01a"
    NCT01b = "NCT01b"
    NCT02a = "NCT02a"
    NCT02b = "NCT02b"
    NCT04a = "NCT04a"
    NCT04b = "NCT04b"
    NCT05a = "NCT05a"
    NCT06a = "NCT06a"
    NCT07a = "NCT07a"
    NCT08a = "NCT08a"
    NCT08b = "NCT08b"
    NCT09a = "NCT09a"
    NCT09b = "NCT09b"
    NCT09c = "NCT09c"
    NCT10a = "NCT10a"
    NCT11a = "NCT11a"
    NCT11b = "NCT11b"
    NCT12a = "NCT12a"
    upcoming_enum = "upcoming_enum"


class PermitCondition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    condition: PermitConditionTypeResponse
    condition_string: str
    comment: str | None = None


class LaneRentalAssessmentOutcomeResponse(Enum):
    chargeable = "chargeable"
    potentially_chargeable = "potentially_chargeable"
    charges_waived = "charges_waived"
    exempt = "exempt"
    charges_not_applicable = "charges_not_applicable"
    upcoming_enum = "upcoming_enum"


class ActivityTypeResponse(Enum):
    highway_improvement_works = "highway_improvement_works"
    highway_repair_and_maintenance_works = "highway_repair_and_maintenance_works"
    utility_asset_works = "utility_asset_works"
    utility_repair_and_maintenance_works = "utility_repair_and_maintenance_works"
    diversionary_works = "diversionary_works"
    disconnection_or_alteration_of_supply = "disconnection_or_alteration_of_supply"
    permanent_reinstatement = "permanent_reinstatement"
    remedial_works = "remedial_works"
    section_58 = "section_58"
    section_50 = "section_50"
    core_sampling = "core_sampling"
    statutory_infrastructure_works = "statutory_infrastructure_works"
    works_for_rail_purposes = "works_for_rail_purposes"
    works_for_road_purposes = "works_for_road_purposes"
    new_service_connection = "new_service_connection"
    optional_permit_no_fee = "optional_permit_no_fee"
    upcoming_enum = "upcoming_enum"


class PermitSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    promoter_swa_code: str
    promoter_organisation: str
    highway_authority: str
    works_coordinates: Any
    location_description: str
    street: str
    town: str
    area: str
    work_category: WorkCategoryResponse
    work_category_string: str
    description_of_work: str
    traffic_management_type: TrafficManagementTypeResponse
    traffic_management_type_string: str
    assessment_status: AssessmentStatusResponse | None = None
    assessment_status_string: str | None = None
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    actual_start_date: AwareDatetime | None = None
    actual_end_date: AwareDatetime | None = None
    status: PermitStatusResponse
    status_string: str
    work_status: WorkStatusResponse
    work_status_string: str
    deadline_date: AwareDatetime
    date_created: AwareDatetime
    status_changed_date: AwareDatetime
    usrn: float
    is_active_permit: bool
    permit_conditions: list[PermitCondition] | None = None
    road_category: float
    is_traffic_sensitive: bool
    has_no_final_reinstatement: bool
    is_deemed: bool
    excavation_carried_out: bool
    is_early_start: bool
    is_high_impact_traffic_management: bool
    is_lane_rental: bool
    lane_rental_assessment_outcome: LaneRentalAssessmentOutcomeResponse | None = None
    lane_rental_assessment_outcome_string: str | None = None
    lane_rental_charges_not_agreed: bool
    lane_rental_charges_potentially_apply: bool
    paa_to_pa_deadline_date: AwareDatetime | None = None
    activity_type: ActivityTypeResponse
    activity_type_string: str


class PermitSearchReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[PermitSummaryResponse]
    next_cursor: float


class PermitSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_numbers: list[str] | None = Field(
        None,
        description="Array values must be unique\nMust not contain null or undefined values\nArray max length 1000\nWork reference numbers have a max length 24 characters",
    )
    next_cursor: float | None = None
    page_size: float | None = Field(
        None,
        description="Minimum value of 100\nMaximum value of 500\nMust be an integer",
    )


class SubscriptionCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subscription_reference_number: str


class SubscriptionCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    api_endpoint: str = Field(..., description="Max length 2048 characters")
    subscription_description: str | None = Field(
        None, description="Max length 100 characters"
    )


class SubscriptionRemoveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    subscription_reference_number: str | None = None


class GetSubscriptionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subscription_reference_number: str
    subscription_description: str
    subscription_url: str
