"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager export API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/export/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmp6mrc3p6f.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CSVExportResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    csv_id: float


class Section81Status(Enum):
    issued = "issued"
    acknowledged = "acknowledged"
    accepted = "accepted"
    accepted_fixed = "accepted_fixed"
    rejected = "rejected"
    resolved_by_ha = "resolved_by_ha"
    cancelled = "cancelled"
    reassigned = "reassigned"


class Section81Severity(Enum):
    high = "high"
    low = "low"


class Section81Type(Enum):
    tee_valve_access_covers = "tee_valve_access_covers"
    cabinet = "cabinet"
    marker_post = "marker_post"
    pole_post = "pole_post"
    overhead_cables_broken_low_encroaching_onto_highway = (
        "overhead_cables_broken_low_encroaching_onto_highway"
    )
    other = "other"
    unattributed_works_live_site = "unattributed_works_live_site"
    unattributed_works_completed = "unattributed_works_completed"


class Section81CSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    status: list[Section81Status] | None = None
    severity: list[Section81Severity] | None = None
    issue_date_from: AwareDatetime | None = None
    issue_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided issue_date_from"
    )
    status_changed_date_from: AwareDatetime | None = None
    status_changed_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided status_changed_date_from"
    )
    type: list[Section81Type] | None = None
    section_81_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class ReinstatementStatus(Enum):
    interim = "interim"
    permanent = "permanent"


class ReinstatementCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    status: list[ReinstatementStatus] | None = None
    latest_reinstatements_only: bool | None = None
    registration_date_from: AwareDatetime | None = None
    registration_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided registration_date_from"
    )
    end_date_from: AwareDatetime | None = None
    end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the end_date_from"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class ExpiringInterimReinstatementCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    registration_date_from: AwareDatetime | None = None
    registration_date_to: AwareDatetime | None = Field(
        None, description="Must occur after or on the provided registration_date_from"
    )
    end_date_from: AwareDatetime | None = None
    end_date_to: AwareDatetime | None = Field(
        None, description="Must occur after or on the provided end_date_from"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class FPNStatus(Enum):
    issued = "issued"
    accepted = "accepted"
    paid = "paid"
    paid_discounted = "paid_discounted"
    disputed = "disputed"
    withdrawn = "withdrawn"


class OffenceCode(Enum):
    offence_code_05 = "offence_code_05"
    offence_code_06 = "offence_code_06"
    offence_code_08 = "offence_code_08"
    offence_code_09 = "offence_code_09"


class FPNCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    status: list[FPNStatus] | None = None
    start_date: AwareDatetime | None = Field(
        None,
        description="start_date must be before or the same as end_date if both are provided",
    )
    end_date: AwareDatetime | None = Field(
        None,
        description="end_date must be the same as or after start_date if both are provided",
    )
    offence_code: list[OffenceCode] | None = None
    status_changed_date_from: AwareDatetime | None = Field(
        None,
        description="status_changed_date_from must be before or the same as status_changed_date_to if both are provided",
    )
    status_changed_date_to: AwareDatetime | None = Field(
        None,
        description="end_date must be the same as or after status_changed_date_from if both are provided",
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class FeeReportFormat(Enum):
    all_orgs_one_csv = "all_orgs_one_csv"
    single_org_one_csv = "single_org_one_csv"
    all_orgs_multiple_csvs = "all_orgs_multiple_csvs"


class FeesCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_date: AwareDatetime = Field(
        ...,
        description="Must be within 30 days of provided end_date\nMust be provided if end_date is provided",
    )
    end_date: AwareDatetime = Field(
        ..., description="Must occur on or after the provided start_date"
    )
    swa_code: str | None = Field(
        None,
        description="Must be provided if user is a contractor\nMax length 4 characters",
    )
    fee_report_format: FeeReportFormat
    swa_code_filter: str | None = Field(
        None,
        description="Required if fee_report_format = single_org_one_csv\nMax length 4 characters",
    )
    export_description: str | None = None


class PermitStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    permit_modification_request = "permit_modification_request"
    refused = "refused"
    closed = "closed"
    cancelled = "cancelled"
    revoked = "revoked"
    progressed = "progressed"
    under_assessment = "under_assessment"


class WorkStatus(Enum):
    planned = "planned"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"
    unattributable = "unattributable"
    historical = "historical"
    non_notifiable = "non_notifiable"
    section_81 = "section_81"


class WorkCategory(Enum):
    minor = "minor"
    standard = "standard"
    major = "major"
    immediate_urgent = "immediate_urgent"
    immediate_emergency = "immediate_emergency"
    paa = "paa"
    hs2_highway = "hs2_highway"


class LaneRentalAssessmentOutcome(Enum):
    chargeable = "chargeable"
    potentially_chargeable = "potentially_chargeable"
    charges_waived = "charges_waived"
    exempt = "exempt"
    charges_not_applicable = "charges_not_applicable"


class PermitCsvExportPrefix(Enum):
    PA = "PA"
    WR = "WR"
    PAA = "PAA"


class PermitCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    status: list[PermitStatus] | None = None
    work_status: list[WorkStatus] | None = None
    work_category: list[WorkCategory] | None = None
    lane_rental_assessment_outcome: list[LaneRentalAssessmentOutcome] | None = None
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date"
    )
    work_start_date_from: AwareDatetime | None = None
    work_start_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided work_start_date_from"
    )
    work_end_date_from: AwareDatetime | None = None
    work_end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided work_end_date_from"
    )
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = None
    active_permit_only: bool | None = None
    csv_export_prefix: PermitCsvExportPrefix | None = None
    is_traffic_sensitive: bool | None = None
    is_high_impact_traffic_management: bool | None = None
    has_no_final_registration: bool | None = None
    has_excavation: bool | None = None
    is_early_start: bool | None = None
    is_deemed: bool | None = None
    lane_rental_charges_not_agreed: bool | None = None
    lane_rental_charges_potentially_apply: bool | None = None
    ever_modification_requested: bool | None = None
    hs2_works_only: bool | None = None
    consultation_works_only: bool | None = None
    consent_works_only: bool | None = None
    unacknowledged_by_ha_only: bool | None = None
    is_duration_challenged: bool | None = None
    permit_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    reasonable_period_end_date_from: AwareDatetime | None = None
    reasonable_period_end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after reasonable_period_end_date_from"
    )


class ReinstatementsDueCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    work_end_date_from: AwareDatetime | None = None
    work_end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided work_start_date_from"
    )
    registration_due_date_from: AwareDatetime | None = None
    registration_due_date_to: AwareDatetime | None = Field(
        None,
        description="Must occur on or after the provided registration_due_date_from",
    )


class InspectionOutcome(Enum):
    passed = "passed"
    unable_to_complete_inspection = "unable_to_complete_inspection"
    failed_low = "failed_low"
    failed_high = "failed_high"
    further_inspections_required = "further_inspections_required"
    agreed_site_compliance = "agreed_site_compliance"
    non_compliant_with_conditions = "non_compliant_with_conditions"
    works_stopped_apparatus_remaining = "works_stopped_apparatus_remaining"
    works_in_progress_no_carriageway_incursion = (
        "works_in_progress_no_carriageway_incursion"
    )
    works_in_progress = "works_in_progress"
    works_stopped = "works_stopped"
    failed = "failed"


class PromoterInspectionOutcomeStatusType(Enum):
    inspection_outcome_accepted = "inspection_outcome_accepted"
    inspection_outcome_disputed = "inspection_outcome_disputed"
    joint_site_meeting_needed = "joint_site_meeting_needed"
    inspection_outcome_promoter_disagrees_with_ha_acceptance_on_behalf = (
        "inspection_outcome_promoter_disagrees_with_ha_acceptance_on_behalf"
    )
    no_response = "no_response"


class HAInspectionOutcomeStatusType(Enum):
    inspection_outcome_promoter_accepts_failed_inspection = (
        "inspection_outcome_promoter_accepts_failed_inspection"
    )
    reviewing_dispute = "reviewing_dispute"
    no_agreement = "no_agreement"
    inspection_withdrawn = "inspection_withdrawn"
    no_response = "no_response"


class InspectionType(Enum):
    live_site = "live_site"
    reinstatement = "reinstatement"
    non_compliance_follow_up = "non_compliance_follow_up"
    section_81 = "section_81"
    investigatory_works = "investigatory_works"


class InspectionCategory(Enum):
    a = "a"
    b = "b"
    c = "c"
    third_party = "third_party"
    routine = "routine"
    joint_site_visit = "joint_site_visit"
    follow_up = "follow_up"
    follow_up_completion = "follow_up_completion"
    site_occupancy = "site_occupancy"
    conditions = "conditions"
    core_sample = "core_sample"
    skid_resistance = "skid_resistance"
    texture_depth = "texture_depth"
    surface_regularity = "surface_regularity"
    trial_hole = "trial_hole"


class InspectionCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date"
    )
    inspection_type: list[InspectionType] | None = None
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = Field(
        None, description="Must occur or or after the provided start_date_created"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    inspection_category: list[InspectionCategory] | None = None
    inspection_outcome: list[InspectionOutcome] | None = None
    promoter_outcome_status: list[PromoterInspectionOutcomeStatusType] | None = None
    ha_outcome_status: list[HAInspectionOutcomeStatusType] | None = None
    is_auto_accepted: bool | None = None


class ForwardPlanStatus(Enum):
    raised = "raised"
    cancelled = "cancelled"
    progressed = "progressed"


class ForwardPlanCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    forward_plan_status: list[ForwardPlanStatus] | None = None
    proposed_start_date: AwareDatetime | None = None
    proposed_end_date: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided proposed_start_date"
    )
    work_start_date_from: AwareDatetime | None = None
    work_start_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided work_start_date_from"
    )
    work_end_date_from: AwareDatetime | None = None
    work_end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided work_end_date_from"
    )
    forward_plan_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class AlterationStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    revoked = "revoked"
    auto_applied = "auto_applied"


class AlterationType(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"


class PermitAlterationCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    alteration_status: list[AlterationStatus] | None = None
    alteration_type: list[AlterationType] | None = None
    work_status: list[WorkStatus] | None = None
    work_category: list[WorkCategory] | None = None
    lane_rental_assessment_outcome: list[LaneRentalAssessmentOutcome] | None = None
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date_created"
    )
    is_traffic_sensitive: bool | None = None
    is_high_impact_traffic_management: bool | None = None
    is_duration_extension: bool | None = None
    is_early_start: bool | None = None
    is_deemed: bool | None = None
    lane_rental_charges_not_agreed: bool | None = None
    lane_rental_charges_potentially_apply: bool | None = None
    status_update_date_from: AwareDatetime | None = None
    status_update_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided status_update_date_from"
    )
    permit_alteration_reference_number: str | None = Field(
        None, description="Max length 105 characters"
    )


class OrganisationDataCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_date: AwareDatetime = Field(
        ...,
        description="Must be within 30 days of provided end_date\nMust be a date in the past",
    )
    start_date_time: AwareDatetime | None = Field(
        None, description="The date must match the date provided in start_date"
    )
    end_date: AwareDatetime = Field(
        ...,
        description="Must be a date in the past\nMust occur on or after the provided start_date",
    )
    end_date_time: AwareDatetime | None = Field(
        None, description="The date must match the date provided in end_date"
    )


class CommentTopic(Enum):
    GENERAL = "GENERAL"
    SECTION_74 = "SECTION_74"
    INSPECTION = "INSPECTION"
    FPN = "FPN"
    OVERRUN = "OVERRUN"
    FORWARD_PLAN = "FORWARD_PLAN"
    CHANGE_REQUEST = "CHANGE_REQUEST"
    IMPOSED_VARIATION = "IMPOSED_VARIATION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    SECTION_81 = "SECTION_81"
    UNATTRIBUTED_WORKS = "UNATTRIBUTED_WORKS"


class CommentCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    date_created_from: AwareDatetime | None = None
    date_created_to: AwareDatetime | None = Field(
        None, description="Must occur after or on provided date_created_from"
    )
    topic: list[CommentTopic] | None = None
    is_internal: bool | None = None
    is_read: bool | None = None
    is_not_read: bool | None = None
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    author_email_address: str | None = Field(
        None, description="Max length 100 characters"
    )
    is_incoming: bool | None = None
    is_outgoing: bool | None = None


class InspectionOutcomesCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class PermitsCreatedCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class FPNsCreatedCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class PermitOutcomesCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class PermitAlterationsCreatedCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class PermitAlterationOutcomesCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class PbiSampleInspectionPassFailRatesCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime


class NumberOfInspectionUnitsCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class Section58Status(Enum):
    proposed = "proposed"
    in_force = "in_force"
    cancelled = "cancelled"
    closed = "closed"


class Section58CSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    ha_organisation_name: str | None = None
    start_date_from: AwareDatetime | None = None
    start_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date_from"
    )
    section_58_status: list[Section58Status] | None = None
    section_58_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class Section74HAStatus(Enum):
    warning_issued = "warning_issued"
    charges_ended = "charges_ended"
    warning_disputed = "warning_disputed"
    withdrawn = "withdrawn"
    draft_invoice_issued = "draft_invoice_issued"
    resolved = "resolved"


class Section74CSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    section_74_ha_status: list[Section74HAStatus] | None = None
    date_created_from: AwareDatetime | None = None
    date_created_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided date_created_from"
    )
    section_74_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class PbiSampleInspectionsDueCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    sample_expiry_date_from: AwareDatetime | None = None
    sample_expiry_date_to: AwareDatetime | None = Field(
        None, description="Must be on or after sample_expiry_date_from"
    )


class CSVExportStatusResponse(Enum):
    queued = "queued"
    in_progress = "in_progress"
    ready = "ready"
    failed = "failed"
    upcoming_enum = "upcoming_enum"


class CSVExportTypeResponse(Enum):
    FEE = "FEE"
    FORWARD_PLAN = "FORWARD_PLAN"
    FPN = "FPN"
    INSPECTION = "INSPECTION"
    PERMIT = "PERMIT"
    REINSTATEMENT = "REINSTATEMENT"
    SECTION_81 = "SECTION_81"
    PERMIT_ALTERATION = "PERMIT_ALTERATION"
    ORGANISATION_DATA = "ORGANISATION_DATA"
    COMMENT = "COMMENT"
    REPORTING_INSPECTION_OUTCOMES = "REPORTING_INSPECTION_OUTCOMES"
    REPORTING_PERMITS_CREATED = "REPORTING_PERMITS_CREATED"
    REPORTING_PERMIT_OUTCOMES = "REPORTING_PERMIT_OUTCOMES"
    REPORTING_ALTERATIONS_CREATED = "REPORTING_ALTERATIONS_CREATED"
    REPORTING_ALTERATION_OUTCOMES = "REPORTING_ALTERATION_OUTCOMES"
    REPORTING_FPNS_CREATED = "REPORTING_FPNS_CREATED"
    REPORTING_PERMITS_DEEMED = "REPORTING_PERMITS_DEEMED"
    SECTION_58 = "SECTION_58"
    SECTION_74 = "SECTION_74"
    SAMPLE_INSPECTIONS_DUE = "SAMPLE_INSPECTIONS_DUE"
    EXPIRING_INTERIM_REINSTATEMENT = "EXPIRING_INTERIM_REINSTATEMENT"
    PBI_SAMPLE_INSPECTIONS_DUE = "PBI_SAMPLE_INSPECTIONS_DUE"
    REPORTING_PBI_PASS_FAIL_RATES = "REPORTING_PBI_PASS_FAIL_RATES"
    NUMBER_OF_INSPECTION_UNITS = "NUMBER_OF_INSPECTION_UNITS"
    PRIVATE_STREET_NOTICE = "PRIVATE_STREET_NOTICE"
    REINSPECTION = "REINSPECTION"
    NON_COMPLIANCE = "NON_COMPLIANCE"
    REINSTATEMENTS_DUE = "REINSTATEMENTS_DUE"
    MATERIAL_CLASSIFICATION = "MATERIAL_CLASSIFICATION"
    PBI_SAMPLE_INSPECTION_TARGET = "PBI_SAMPLE_INSPECTION_TARGET"
    INTERESTED_PARTY_PERMIT = "INTERESTED_PARTY_PERMIT"
    CHANGE_REQUEST = "CHANGE_REQUEST"
    upcoming_enum = "upcoming_enum"


class CSVExportDetailsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    csv_export_id: float
    filename: str
    date_created: AwareDatetime
    csv_export_status: CSVExportStatusResponse
    csv_export_status_string: str
    filters: Any
    csv_export_type: CSVExportTypeResponse
    csv_export_type_string: str
    export_description: str | None = None


class PrivateStreetStatus(Enum):
    cancelled = "cancelled"
    issued = "issued"


class PrivateStreetCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    private_street_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    start_date_from: AwareDatetime | None = None
    start_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after start_date_from"
    )
    end_date_from: AwareDatetime | None = None
    end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after end_date_from"
    )
    date_created_from: AwareDatetime | None = None
    date_created_to: AwareDatetime | None = Field(
        None, description="Must occur on or after date_created_from"
    )
    private_street_status: list[PrivateStreetStatus] | None = None


class ReinspectionCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date"
    )
    inspection_type: list[InspectionType] | None = None
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = Field(
        None, description="Must occur or or after the provided start_date_created"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    inspection_category: list[InspectionCategory] | None = None


class NonComplianceStatus(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    resolved = "resolved"


class NonComplianceResponseStatus(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    works_completed_and_passed = "works_completed_and_passed"
    joint_site_meeting_suggested = "joint_site_meeting_suggested"
    will_attend_joint_site_meeting = "will_attend_joint_site_meeting"
    works_complete_ready_for_inspection = "works_complete_ready_for_inspection"
    joint_site_meeting_not_needed = "joint_site_meeting_not_needed"
    accept_suggestion = "accept_suggestion"
    no_response = "no_response"


class NonComplianceCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    non_compliance_reference_number: str | None = Field(
        None, description="Max length 106 characters"
    )
    non_compliance_status: list[NonComplianceStatus] | None = None
    ha_response_status: list[NonComplianceResponseStatus] | None = None
    promoter_response_status: list[NonComplianceResponseStatus] | None = None
    non_compliance_date_created_from: AwareDatetime | None = None
    non_compliance_date_created_to: AwareDatetime | None = Field(
        None, description="Must occur on or after non_compliance_date_created_from"
    )
    most_recent_inspection_type: list[InspectionType] | None = None
    most_recent_inspection_outcome: list[InspectionOutcome] | None = None
    most_recent_inspection_promoter_response_status: (
        list[PromoterInspectionOutcomeStatusType] | None
    ) = None
    most_recent_inspection_ha_response_status: (
        list[HAInspectionOutcomeStatusType] | None
    ) = None


class MaterialClassificationClassification(Enum):
    hazardous = "hazardous"
    non_hazardous = "non_hazardous"


class MaterialClassificationCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    material_classification_classification: MaterialClassificationClassification
    material_classification_reference_number: str | None = Field(
        None, description="Max length 50 characters"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    sample_date_from: AwareDatetime | None = None
    sample_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after sample_date_from"
    )
    date_created_from: AwareDatetime | None = None
    date_created_to: AwareDatetime | None = Field(
        None, description="Must occur on or after date_created_from"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")


class PbiSampleInspectionTargetCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_from: AwareDatetime
    date_to: AwareDatetime


class InterestedPartyPermitsCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    permit_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    work_reference_number: str | None = Field(
        None, description="Max length 100 characters"
    )
    work_start_date_from: AwareDatetime | None = None
    work_start_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after work_start_date_from"
    )
    work_end_date_from: AwareDatetime | None = None
    work_end_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after work_end_date_from"
    )
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = Field(
        None, description="Must occur on or after start_date_created"
    )
    work_status: list[WorkStatus] | None = None
    work_category: list[WorkCategory] | None = None
    is_high_impact_traffic_management: bool | None = None
    promoter_organisation_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    ha_organisation_name: str | None = Field(
        None, description="Max length 100 characters"
    )


class ChangeRequestStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    revoked = "revoked"
    auto_applied = "auto_applied"


class ChangeRequestType(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"


class ChangeRequestCSVExportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: list[str] | None = Field(
        None, description="Array values must be unique"
    )
    street_descriptor: str | None = Field(None, description="Max length 100 characters")
    usrn: str | None = Field(None, description="Max length 100 characters")
    swa_code: str | None = Field(
        None, description="Must be provided if user is a contractor\nUp to four digits"
    )
    export_description: str | None = Field(None, description="Max length 50 characters")
    organisation: str | None = Field(None, description="Max length 100 characters")
    change_request_status: list[ChangeRequestStatus] | None = None
    change_request_type: list[ChangeRequestType] | None = None
    work_category: list[WorkCategory] | None = None
    start_date_created: AwareDatetime | None = None
    end_date_created: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided start_date_created"
    )
    is_traffic_sensitive: bool | None = None
    is_high_impact_traffic_management: bool | None = None
    status_update_date_from: AwareDatetime | None = None
    status_update_date_to: AwareDatetime | None = Field(
        None, description="Must occur on or after the provided status_update_date_from"
    )
    change_request_reference_number: str | None = Field(
        None, description="Max length 105 characters"
    )
