"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager geojson API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/geojson/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmpi30h3z4g.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class WorkCategoryResponse(Enum):
    minor = "minor"
    standard = "standard"
    major = "major"
    immediate_urgent = "immediate_urgent"
    immediate_emergency = "immediate_emergency"
    paa = "paa"
    hs2_highway = "hs2_highway"
    upcoming_enum = "upcoming_enum"


class TrafficManagementTypeResponse(Enum):
    road_closure = "road_closure"
    contra_flow = "contra_flow"
    lane_closure = "lane_closure"
    multi_way_signals = "multi_way_signals"
    two_way_signals = "two_way_signals"
    convoy_workings = "convoy_workings"
    stop_go_boards = "stop_go_boards"
    priority_working = "priority_working"
    give_and_take = "give_and_take"
    some_carriageway_incursion = "some_carriageway_incursion"
    no_carriageway_incursion = "no_carriageway_incursion"
    temp_obstruction_15_minute_delay = "temp_obstruction_15_minute_delay"
    upcoming_enum = "upcoming_enum"


class GeoJSONCentrePointType(Enum):
    Point = "Point"


class GeoJSONCentrePoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeoJSONCentrePointType
    coordinates: list[float]


class PermitStatusResponse(Enum):
    submitted = "submitted"
    granted = "granted"
    permit_modification_request = "permit_modification_request"
    refused = "refused"
    closed = "closed"
    cancelled = "cancelled"
    revoked = "revoked"
    progressed = "progressed"
    upcoming_enum = "upcoming_enum"


class IndustrySectorResponse(Enum):
    electric = "electric"
    water = "water"
    gas = "gas"
    telecoms = "telecoms"
    transport = "transport"
    highway_authority = "highway_authority"
    other = "other"
    upcoming_enum = "upcoming_enum"


class WorkProperties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    promoter_organisation: str
    promoter_swa_code: str
    work_category: WorkCategoryResponse
    work_category_string: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    traffic_management_type: TrafficManagementTypeResponse
    traffic_management_type_string: str
    current_traffic_management_type: TrafficManagementTypeResponse | None = None
    current_traffic_management_type_string: str | None = None
    current_traffic_management_update_date: AwareDatetime | None = None
    street: str
    usrn: float
    town: str
    area: str
    highway_authority: str
    work_centre_point: GeoJSONCentrePoint = Field(
        ..., description="GeoJSON Point Geometry"
    )
    permit_status: PermitStatusResponse
    permit_status_string: str
    industry_sector: IndustrySectorResponse | None = None
    industry_sector_string: str | None = None


class FeatureType(Enum):
    Feature = "Feature"


class GeoJSONFeatureTypeResponse(Enum):
    Point = "Point"
    LineString = "LineString"
    Polygon = "Polygon"
    upcoming_enum = "upcoming_enum"


class GeoJSONGeometry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeoJSONFeatureTypeResponse
    type_string: str
    coordinates: list[Any]


class WorkFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: WorkProperties


class FeatureCollectionType(Enum):
    FeatureCollection = "FeatureCollection"


class WorkResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[WorkFeature]


class ActivityActivityTypeResponse(Enum):
    skips = "skips"
    scaffolding = "scaffolding"
    hoarding = "hoarding"
    crane_mobile_platform = "crane_mobile_platform"
    event = "event"
    section50 = "section50"
    section58 = "section58"
    compound = "compound"
    other = "other"
    upcoming_enum = "upcoming_enum"


class ActivityProperties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity_centre_point: GeoJSONCentrePoint = Field(
        ..., description="GeoJSON Point Geometry"
    )
    activity_name: str
    activity_location_description: str
    activity_reference_number: str
    activity_type: ActivityActivityTypeResponse
    activity_type_string: str
    area_name: str
    cancelled: bool
    end_date: AwareDatetime
    street_name: str
    start_date: AwareDatetime


class ActivityFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: ActivityProperties


class ActivityResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[ActivityFeature]


class ForwardPlanStatusResponse(Enum):
    raised = "raised"
    cancelled = "cancelled"
    progressed = "progressed"
    upcoming_enum = "upcoming_enum"


class ForwardPlanProperties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    forward_plan_reference_number: str
    work_reference_number: str
    forward_plan_status: ForwardPlanStatusResponse
    forward_plan_status_string: str
    work_centre_point: GeoJSONCentrePoint = Field(
        ..., description="GeoJSON Point Geometry"
    )
    street: str
    area: str | None = None
    start_date: AwareDatetime
    end_date: AwareDatetime
    description_of_work: str
    promoter_organisation: str
    location_description: str


class ForwardPlanFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: ForwardPlanProperties


class ForwardPlanResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[ForwardPlanFeature]


class Hs2ActLimitsFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")


class Hs2ActLimitsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[Hs2ActLimitsFeature]


class Hs2ActLimitPhase(Enum):
    phase_1 = "phase_1"
    phase_2a = "phase_2a"


class Section58StatusResponse(Enum):
    proposed = "proposed"
    in_force = "in_force"
    cancelled = "cancelled"
    closed = "closed"
    upcoming_enum = "upcoming_enum"


class Section58DurationResponse(Enum):
    six_months = "six_months"
    one_year = "one_year"
    two_years = "two_years"
    three_years = "three_years"
    upcoming_enum = "upcoming_enum"


class Section58ExtentResponse(Enum):
    whole_road = "whole_road"
    part_of_the_road = "part_of_the_road"
    upcoming_enum = "upcoming_enum"


class LocationTypeResponse(Enum):
    footway = "footway"
    carriageway = "carriageway"
    verge = "verge"
    cycleway = "cycleway"
    footpath = "footpath"
    parking_place = "parking_place"
    bus_stop_or_stand = "bus_stop_or_stand"
    cycle_hire_docking_station = "cycle_hire_docking_station"
    taxi_rank = "taxi_rank"
    upcoming_enum = "upcoming_enum"


class Section58Properties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    section_58_centre_point: GeoJSONCentrePoint
    section_58_reference_number: str
    section_58_status: Section58StatusResponse
    section_58_status_string: str
    street_name: str
    area_name: str | None = None
    organisation_name: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    restriction_duration: Section58DurationResponse
    restriction_duration_string: str
    restriction_extent: Section58ExtentResponse
    restriction_extent_string: str
    location_types: list[LocationTypeResponse]
    location_types_string: list[str]


class Section58Feature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: Section58Properties


class Section58Response(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[Section58Feature]


class AncillaryInfoTypeResponse(Enum):
    portable_traffic_signals_or_other_traffic_controls = (
        "portable_traffic_signals_or_other_traffic_controls"
    )
    site_welfare_facilities = "site_welfare_facilities"
    site_compound_or_material_storage = "site_compound_or_material_storage"
    site_compound_for_works = "site_compound_for_works"
    upcoming_enum = "upcoming_enum"


class AncillaryInfoStatusResponse(Enum):
    added = "added"
    removed = "removed"
    upcoming_enum = "upcoming_enum"


class AncillaryInfoProperties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str | None = None
    permit_reference_number: str | None = None
    ancillary_info_reference_number: str
    location_description: str
    ancillary_info_type: AncillaryInfoTypeResponse
    ancillary_info_status: AncillaryInfoStatusResponse
    ancillary_info_type_string: str
    ancillary_info_status_string: str
    ancillary_info_centre_point: GeoJSONCentrePoint = Field(
        ..., description="GeoJSON Point Geometry"
    )
    ancillary_info_coordinates: list[Any]
    promoter_organisation: str
    date_created: AwareDatetime
    usrns: list[float]


class AncillaryInfoFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: AncillaryInfoProperties


class AncillaryInfoResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[AncillaryInfoFeature]


class MaterialClassificationClassificationResponse(Enum):
    hazardous = "hazardous"
    non_hazardous = "non_hazardous"
    upcoming_enum = "upcoming_enum"


class MaterialClassificationMaterialTypeResponse(Enum):
    coal_tar = "coal_tar"
    total_petroleum_hydrocarbons = "total_petroleum_hydrocarbons"
    ph = "ph"
    heavy_metal = "heavy_metal"
    asbestos = "asbestos"
    other = "other"
    upcoming_enum = "upcoming_enum"


class MaterialClassificationProperties(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    material_classification_reference_number: str
    material_classification_classification: MaterialClassificationClassificationResponse
    material_classification_classification_string: str
    sample_date: AwareDatetime
    recorded_by_swa_code: str
    recorded_by_organisation_name: str
    usrn: float
    material_type: list[MaterialClassificationMaterialTypeResponse] | None = None
    material_type_string: list[str] | None = None
    material_classification_centre_point: GeoJSONCentrePoint = Field(
        ..., description="GeoJSON Point Geometry"
    )


class MaterialClassificationFeature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureType
    geometry: GeoJSONGeometry = Field(..., description="GeoJSON Geometry")
    properties: MaterialClassificationProperties


class MaterialClassificationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FeatureCollectionType
    features: list[MaterialClassificationFeature]


class MaterialClassificationClassification(Enum):
    hazardous = "hazardous"
    non_hazardous = "non_hazardous"


class PotentialClashSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    start_date: AwareDatetime
    end_date: AwareDatetime


class PotentialClashesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    works: list[PotentialClashSummaryResponse]


class PotentialCollaborationsSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    start_date: AwareDatetime
    end_date: AwareDatetime


class PotentialCollaborationsAndClashesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    collaborations: list[PotentialCollaborationsSummaryResponse]
    clashes: list[PotentialClashSummaryResponse] | None = None
