"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager lookup API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/lookup/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmpetrox8_g.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ReinstatementTypeCodeResponse(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7
    number_8 = 8
    number_9 = 9
    number_10 = 10
    number_999 = 999


class ReinstatementTypeDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reinstatement_type_code: ReinstatementTypeCodeResponse
    reinstatement_type_code_string: str
    reinstatement_type_location_text: str | None = None
    is_active: bool


class PrimaryNoticeAuthority(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    swa_code: str
    name: str
    location_description: str
    record_end_date: AwareDatetime | None = None


class InterestAuthority(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    location_description: str
    swa_code: str
    record_end_date: AwareDatetime | None = None


class AdditionalSpecialDesignationCodeResponse(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_6 = 6
    number_8 = 8
    number_9 = 9
    number_10 = 10
    number_12 = 12
    number_13 = 13
    number_16 = 16
    number_17 = 17
    number_18 = 18
    number_19 = 19
    number_20 = 20
    number_21 = 21
    number_22 = 22
    number_23 = 23
    number_24 = 24
    number_25 = 25
    number_26 = 26
    number_27 = 27
    number_28 = 28
    number_29 = 29
    number_30 = 30
    number_999 = 999


class AdditionalSpecialDesignationsPeriodicityCodeResponse(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_7 = 7
    number_8 = 8
    number_9 = 9
    number_10 = 10
    number_11 = 11
    number_12 = 12
    number_13 = 13
    number_14 = 14
    number_15 = 15
    number_16 = 16
    number_999 = 999


class GeoJSONFeatureTypeResponse(Enum):
    Point = "Point"
    LineString = "LineString"
    Polygon = "Polygon"
    MultiLineString = "MultiLineString"
    upcoming_enum = "upcoming_enum"


class GeoJSONGeometry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeoJSONFeatureTypeResponse
    type_string: str
    coordinates: Any


class AdditionalSpecialDesignationsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    street_special_desig_code: AdditionalSpecialDesignationCodeResponse
    street_special_desig_code_string: str | None = None
    special_desig_location_text: str | None = None
    special_desig_description: str | None = None
    special_desig_start_time: float | None = None
    special_desig_end_time: float | None = None
    special_desig_periodicity_code: (
        AdditionalSpecialDesignationsPeriodicityCodeResponse | None
    ) = None
    special_desig_periodicity_code_string: str | None = None
    asd_coordinate_geometry: GeoJSONGeometry | None = None
    whole_road: bool | None = None
    special_desig_start_date: AwareDatetime | None = None
    special_desig_end_date: AwareDatetime | None = None


class GeoJSONMultiLineStringType(Enum):
    MultiLineString = "MultiLineString"


class GeoJSONMultiLineString(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeoJSONMultiLineStringType
    coordinates: list[list[list[float]]]


class GeoJSONCentrePointType(Enum):
    Point = "Point"


class GeoJSONCentrePoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeoJSONCentrePointType
    coordinates: list[float]


class StreetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    usrn: float
    street_descriptor: str
    area: str
    town: str
    authority: str
    authority_swa_code: str
    road_category: float = Field(..., description="DEPRECATED")
    reinstatement_types: list[ReinstatementTypeDetails]
    traffic_sensitive: bool
    primary_notice_authorities: list[PrimaryNoticeAuthority]
    interest_authorities: list[InterestAuthority]
    additional_special_designations_response: list[
        AdditionalSpecialDesignationsResponse
    ]
    street_line: GeoJSONMultiLineString | None = None
    street_centre_point: GeoJSONCentrePoint | None = None


class Coordinates(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    easting: float
    northing: float


class StreetsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    coordinates: list[Coordinates] = Field(
        ...,
        description="Minimum size of 1\nMaximum size of 10\nEach element must be unique",
    )


class UsrnStreetRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    usrns: list[float] = Field(
        ...,
        description="Minimum size of 1\nMaximum size of 25\nEach element must be a minimum value of 100001 and a maximum value of 99999999\nEach element must be unique\nEach element must be a whole number",
    )


class StreetSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    street_descriptor: str
    area: str
    town: str
    usrn: float
    administrative_area: str
    street_centre_point: GeoJSONCentrePoint
