"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager party API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/party/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmp3u3vhoqg.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class WorkstreamStatusResponse(Enum):
    active = "active"
    deactivated = "deactivated"
    upcoming_enum = "upcoming_enum"


class WorkstreamResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: WorkstreamStatusResponse
    status_string: str
    prefix: str
    name: str
    description: str | None = None
    contact_name: str | None = None
    contact_number: str | None = None
    contact_email: str | None = None
    emergency_contact_name: str | None = None
    emergency_contact_number: str | None = None
    organisation_reference: str


class WorkstreamCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prefix: str


class WorkstreamCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    prefix: str = Field(..., description="Must consist of 3 positive whole numbers")
    name: str = Field(..., description="Max length 60 characters")
    description: str | None = Field(None, description="Max length 500 characters")
    contact_name: str | None = Field(None, description="Max length 50 characters")
    contact_number: str | None = Field(None, description="Max length 20 characters")
    contact_email: str | None = Field(None, description="Max length 320 characters")
    emergency_contact_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    emergency_contact_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class WorkstreamUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    name: str = Field(..., description="Max length 60 characters")
    description: str | None = Field(None, description="Max length 500 characters")
    contact_name: str | None = Field(None, description="Max length 50 characters")
    contact_number: str | None = Field(None, description="Max length 20 characters")
    contact_email: str | None = Field(None, description="Max length 320 characters")
    emergency_contact_name: str | None = Field(
        None, description="Max length 100 characters"
    )
    emergency_contact_number: str | None = Field(
        None, description="Max length 100 characters"
    )


class OrganisationTypeResponse(Enum):
    PROMOTER = "PROMOTER"
    HA = "HA"
    CONTRACTOR = "CONTRACTOR"
    upcoming_enum = "upcoming_enum"


class OrganisationStatusResponse(Enum):
    active = "active"
    suspended = "suspended"
    disabled = "disabled"
    upcoming_enum = "upcoming_enum"


class OrganisationSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    organisation_reference: str
    organisation_status: OrganisationStatusResponse | None = None
    organisation_status_string: str | None = None


class IndustrySectorResponse(Enum):
    electric = "electric"
    water = "water"
    gas = "gas"
    telecoms = "telecoms"
    transport = "transport"
    highway_authority = "highway_authority"
    other = "other"
    upcoming_enum = "upcoming_enum"


class OrganisationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    organisation_reference: str
    organisation_status: OrganisationStatusResponse | None = None
    organisation_status_string: str | None = None
    address_line_one: str
    address_line_two: str | None = None
    email: str | None = None
    locality: str | None = None
    phone_number: str
    postcode: str
    town: str | None = None
    prefix: str
    organisation_type: OrganisationTypeResponse
    organisation_type_string: str
    contractors: list[OrganisationSummaryResponse] | None = None
    is_hs2_applicable: bool
    primary_contact_name: str | None = None
    primary_contact_email: str | None = None
    primary_contact_number: str | None = None
    primary_admin_name: str | None = None
    primary_admin_email: str | None = None
    primary_admin_number: str | None = None
    industry_sector: IndustrySectorResponse | None = None
    industry_sector_string: str | None = None


class OrganisationType(Enum):
    PROMOTER = "PROMOTER"
    HA = "HA"
    CONTRACTOR = "CONTRACTOR"


class IndustrySector(Enum):
    electric = "electric"
    water = "water"
    gas = "gas"
    telecoms = "telecoms"
    transport = "transport"
    highway_authority = "highway_authority"
    other = "other"


class OrganisationUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_line_one: str = Field(
        ..., description="Max length 255 characters\nAlphanumeric characters only"
    )
    address_line_two: str | None = Field(
        None, description="Max length 255 characters\nAlphanumeric characters only"
    )
    locality: str | None = Field(
        None, description="Max length 255 characters\nAlphanumeric characters only"
    )
    town: str | None = Field(
        None, description="Max length 255 characters\nAlphanumeric characters only"
    )
    postcode: str = Field(
        ..., description="Max length 8 characters\nAlphanumeric characters only"
    )
    email: str | None = Field(
        None, description="Max length 320 characters\nMust be valid email"
    )
    phone_number: str = Field(..., description="Max length 20 characters")
    primary_contact_name: str = Field(..., description="Max length 100 characters")
    primary_contact_email: str = Field(
        ..., description="Max length 100 characters\nMust be valid email"
    )
    primary_contact_number: str = Field(..., description="Max length 20 characters")
    primary_admin_name: str = Field(..., description="Max length 100 characters")
    primary_admin_email: str = Field(
        ..., description="Max length 100 characters\nMust be valid email"
    )
    primary_admin_number: str = Field(..., description="Max length 20 characters")
    industry_sector: IndustrySector | None = Field(
        None,
        description="Must be a valid IndustrySector\nMandatory if organisation is PROMOTER or HIGHWAY AUTHORITY",
    )


class PaymentMethod(Enum):
    bank_transfer = "bank_transfer"
    card_payment = "card_payment"
    cash = "cash"
    cheque = "cheque"


class UpdateOrganisationFpnDetailsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorised_officer_name: str
    payment_methods: list[PaymentMethod] | None = None
    authorised_officer_contact_details: str | None = None
    authorised_officer_address: str | None = None
    representations_contact_details: str | None = None
    representations_contact_address: str | None = None


class PaymentMethodResponse(Enum):
    bank_transfer = "bank_transfer"
    card_payment = "card_payment"
    cash = "cash"
    cheque = "cheque"
    upcoming_enum = "upcoming_enum"


class OrganisationFpnDetailsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organisation_reference: str
    authorised_officer_name: str
    authorised_officer_contact_details: str | None = None
    authorised_officer_address: str | None = None
    representations_contact_details: str | None = None
    representations_contact_address: str | None = None
    payment_methods: list[PaymentMethodResponse] | None = None
    payment_methods_string: list[str] | None = None


class RoleResponse(Enum):
    Planner = "Planner"
    HighwayAuthority = "HighwayAuthority"
    Admin = "Admin"
    Contractor = "Contractor"
    API = "API"
    UI = "UI"
    DataExport = "DataExport"
    StreetWorksAdmin = "StreetWorksAdmin"
    upcoming_enum = "upcoming_enum"


class WorkstreamAccessLevelResponse(Enum):
    full_write = "full_write"
    read_only = "read_only"
    upcoming_enum = "upcoming_enum"


class UserWorkstreamAccessDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workstream_prefix: str
    access_level: WorkstreamAccessLevelResponse
    workstream_name: str
    access_level_string: str


class PermissionResponse(Enum):
    Permit = "Permit"
    Compliance = "Compliance"
    Work = "Work"
    upcoming_enum = "upcoming_enum"


class RolePermissionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: RoleResponse
    role_string: str
    permissions: list[PermissionResponse]
    permissions_string: list[str]


class UserResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_name: str | None = None
    last_name: str | None = None
    organisation_name: str
    roles: list[RoleResponse] | None = None
    roles_string: list[str] | None = None
    organisation_reference: str
    contracts: list[OrganisationSummaryResponse] | None = None
    workstreams: list[UserWorkstreamAccessDetails] | None = None
    organisation_status: OrganisationStatusResponse | None = None
    organisation_status_string: str | None = None
    role_permissions: list[RolePermissionsResponse] | None = None


class UpdateUserDetailsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_name: str = Field(..., description="Max length 50 characters")
    last_name: str = Field(..., description="Max length 50 characters")


class WorkstreamAccessLevel(Enum):
    full_write = "full_write"
    read_only = "read_only"


class UserWorkstreamAccess(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workstream_prefix: str
    access_level: WorkstreamAccessLevel


class UserWorkstreamAccessUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_workstream_access: list[UserWorkstreamAccess]


class UserForgotPasswordRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str


class UserResetPasswordRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str
    verification_code: str
    password: str


class OrganisationContractCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractor_organisation_reference: str = Field(
        ..., description="Must be organisation reference of a contractor"
    )


class TokenRefreshResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id_token: str
    access_token: str


class TokenRefreshRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refresh_token: str


class LogoutRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_token: str


class Role(Enum):
    Planner = "Planner"
    HighwayAuthority = "HighwayAuthority"
    Admin = "Admin"
    Contractor = "Contractor"
    API = "API"
    UI = "UI"
    DataExport = "DataExport"
    StreetWorksAdmin = "StreetWorksAdmin"


class InviteUserRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str = Field(..., description="Max length 100 characters")
    first_name: str = Field(..., description="Max length 50 characters")
    last_name: str = Field(..., description="Max length 50 characters")
    role: Role | None = None


class SetPasswordResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    idToken: str
    organisationReference: str
    accessToken: str
    refreshToken: str


class SetPasswordRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str
    password: str
    token: str


class RemoveUserRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str = Field(..., description="Max length 50 characters\nMust be valid email")


class RemoveMultipleUsersRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    emails: list[str]


class OnboardUserRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str = Field(..., description="Max length 100 characters")
    first_name: str = Field(..., description="Max length 50 characters")
    last_name: str = Field(..., description="Max length 50 characters")
    organisation_reference: str = Field(..., description="Max length 20 characters")
    roles: list[Role]


class ReOnboardUserRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str = Field(..., description="Max length 100 characters")
    password: str | None = Field(None, description="Max length 99 characters")


class Permission(Enum):
    Permit = "Permit"
    Compliance = "Compliance"
    Work = "Work"


class InternalUpdateUserRolesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    roles: list[Role] = Field(..., description="Each element must be unique")
    permissions: list[Permission] | None = Field(
        None, description="Each element must be unique"
    )
    access_level: WorkstreamAccessLevel | None = None
    workstream_prefixes: list[str] | None = Field(
        None, description="Each element must be unique"
    )


class AdminUpdateUserRolesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    roles: list[Role] = Field(
        ...,
        description="Each element must be unique\nMust be a valid combination of roles",
    )
    permissions: list[Permission] | None = Field(
        None, description="Each element must be unique"
    )


class UserCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str = Field(..., description="Max length 100 characters")
    first_name: str = Field(..., description="Max length 50 characters")
    last_name: str = Field(..., description="Max length 50 characters")
    password: str = Field(..., description="Max length 99 characters")
    organisation_reference: str | None = Field(
        None,
        description="If provided, this must match a registered organisation reference",
    )
    roles: list[Role]
    permissions: list[Permission] | None = None
