"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager reporting API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/reporting/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmp_f029249.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict


class ActivityActivityTypeResponse(Enum):
    skips = "skips"
    scaffolding = "scaffolding"
    hoarding = "hoarding"
    crane_mobile_platform = "crane_mobile_platform"
    event = "event"
    section50 = "section50"
    section58 = "section58"
    compound = "compound"
    other = "other"
    upcoming_enum = "upcoming_enum"


class TrafficManagementTypeResponse(Enum):
    road_closure = "road_closure"
    contra_flow = "contra_flow"
    lane_closure = "lane_closure"
    multi_way_signals = "multi_way_signals"
    two_way_signals = "two_way_signals"
    convoy_workings = "convoy_workings"
    stop_go_boards = "stop_go_boards"
    priority_working = "priority_working"
    give_and_take = "give_and_take"
    some_carriageway_incursion = "some_carriageway_incursion"
    no_carriageway_incursion = "no_carriageway_incursion"
    temp_obstruction_15_minute_delay = "temp_obstruction_15_minute_delay"
    upcoming_enum = "upcoming_enum"


class ActivitySummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity_reference_number: str
    usrn: float
    street_name: str
    town: str
    area_name: str
    road_category: float
    activity_coordinates: Any
    activity_name: str
    activity_activity_type: ActivityActivityTypeResponse
    activity_activity_type_string: str
    activity_type_details: str | None = None
    contact_name: str
    contact_details: str
    start_date: AwareDatetime
    start_time: AwareDatetime | None = None
    end_date: AwareDatetime
    end_time: AwareDatetime | None = None
    activity_location_description: str
    traffic_management_required: bool
    traffic_management_type: TrafficManagementTypeResponse
    traffic_management_type_string: str
    collaborative_working: bool
    additional_info: str
    cancelled: bool
    cancelled_reason: str | None = None
    ha_organisation_name: str
    date_created: AwareDatetime


class PaginationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_rows: float
    has_next_page: bool


class ActivityReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ActivitySummaryResponse]


class ActivityActivityType(Enum):
    skips = "skips"
    scaffolding = "scaffolding"
    hoarding = "hoarding"
    crane_mobile_platform = "crane_mobile_platform"
    event = "event"
    section50 = "section50"
    section58 = "section58"
    compound = "compound"
    other = "other"


class ActivitySortColumn(Enum):
    date_created = "date_created"


class SortDirection(Enum):
    asc = "asc"
    desc = "desc"


class WorkStatusResponse(Enum):
    planned = "planned"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"
    unattributable = "unattributable"
    historical = "historical"
    non_notifiable = "non_notifiable"
    section_81 = "section_81"
    upcoming_enum = "upcoming_enum"


class WorkCategoryResponse(Enum):
    minor = "minor"
    standard = "standard"
    major = "major"
    immediate_urgent = "immediate_urgent"
    immediate_emergency = "immediate_emergency"
    paa = "paa"
    hs2_highway = "hs2_highway"
    upcoming_enum = "upcoming_enum"


class AlterationStatusResponse(Enum):
    submitted = "submitted"
    granted = "granted"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    revoked = "revoked"
    auto_applied = "auto_applied"
    upcoming_enum = "upcoming_enum"


class AlterationTypeResponse(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"
    upcoming_enum = "upcoming_enum"


class LaneRentalAssessmentOutcomeResponse(Enum):
    chargeable = "chargeable"
    potentially_chargeable = "potentially_chargeable"
    charges_waived = "charges_waived"
    exempt = "exempt"
    charges_not_applicable = "charges_not_applicable"
    upcoming_enum = "upcoming_enum"


class AlterationSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    alteration_reference_number: str
    street: str
    town: str
    area: str
    location_description: str
    highway_authority: str
    promoter: str
    work_status: WorkStatusResponse
    work_status_string: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    work_category: WorkCategoryResponse
    work_category_string: str
    alteration_status: AlterationStatusResponse
    alteration_status_string: str
    alteration_type: AlterationTypeResponse
    alteration_type_string: str
    date_created: AwareDatetime
    deadline_date: AwareDatetime
    status_changed_date: AwareDatetime
    lane_rental_assessment_outcome: LaneRentalAssessmentOutcomeResponse | None = None
    lane_rental_assessment_outcome_string: str | None = None
    lane_rental_charges_not_agreed: bool
    lane_rental_charges_potentially_apply: bool


class AlterationReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[AlterationSummaryResponse]


class AlterationStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    revoked = "revoked"
    auto_applied = "auto_applied"


class AlterationType(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"


class WorkStatus(Enum):
    planned = "planned"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"
    unattributable = "unattributable"
    historical = "historical"
    non_notifiable = "non_notifiable"
    section_81 = "section_81"


class WorkCategory(Enum):
    minor = "minor"
    standard = "standard"
    major = "major"
    immediate_urgent = "immediate_urgent"
    immediate_emergency = "immediate_emergency"
    paa = "paa"
    hs2_highway = "hs2_highway"


class LaneRentalAssessmentOutcome(Enum):
    chargeable = "chargeable"
    potentially_chargeable = "potentially_chargeable"
    charges_waived = "charges_waived"
    exempt = "exempt"
    charges_not_applicable = "charges_not_applicable"


class AlterationSortColumn(Enum):
    date_created = "date_created"
    proposed_start_date = "proposed_start_date"
    proposed_end_date = "proposed_end_date"
    status_changed_date = "status_changed_date"


class DurationChallengeReviewStatusResponse(Enum):
    duration_challenge_accepted = "duration_challenge_accepted"
    duration_challenge_not_accepted = "duration_challenge_not_accepted"
    no_response = "no_response"
    upcoming_enum = "upcoming_enum"


class DurationChallengeNonAcceptanceResponseStatusResponse(Enum):
    reasonable_period_end_date_changed = "reasonable_period_end_date_changed"
    reasonable_period_end_date_not_changed = "reasonable_period_end_date_not_changed"
    no_response = "no_response"
    upcoming_enum = "upcoming_enum"


class AlterationDurationChallengeSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    alteration_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    usrn: float
    promoter_swa_code: str
    promoter_organisation: str
    highway_authority: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    actual_start_date: AwareDatetime | None = None
    actual_end_date: AwareDatetime | None = None
    reasonable_period_end_date: AwareDatetime
    status_changed_date: AwareDatetime
    duration_challenge_review_status: DurationChallengeReviewStatusResponse | None = (
        None
    )
    duration_challenge_review_status_string: str | None = None
    duration_challenge_review_update_date: AwareDatetime | None = None
    duration_challenge_non_acceptance_response_status: (
        DurationChallengeNonAcceptanceResponseStatusResponse | None
    ) = None
    duration_challenge_non_acceptance_response_status_string: str | None = None
    duration_challenge_non_acceptance_response_update_date: AwareDatetime | None = None
    duration_challenge_follow_up_review_complete: bool | None = None
    work_status: WorkStatusResponse
    work_status_string: str


class AlterationDurationChallengeReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[AlterationDurationChallengeSummaryResponse]


class AlterationDurationChallengeSortColumn(Enum):
    status_changed_date = "status_changed_date"


class DurationChallengeReviewStatus(Enum):
    duration_challenge_accepted = "duration_challenge_accepted"
    duration_challenge_not_accepted = "duration_challenge_not_accepted"
    no_response = "no_response"


class DurationChallengeNonAcceptanceResponseStatus(Enum):
    reasonable_period_end_date_changed = "reasonable_period_end_date_changed"
    reasonable_period_end_date_not_changed = "reasonable_period_end_date_not_changed"
    no_response = "no_response"


class AssessmentStatusResponse(Enum):
    granted = "granted"
    granted_auto = "granted_auto"
    refused = "refused"
    refused_auto = "refused_auto"
    permit_modification_request = "permit_modification_request"
    revoked = "revoked"
    upcoming_enum = "upcoming_enum"


class PermitStatusResponse(Enum):
    submitted = "submitted"
    granted = "granted"
    permit_modification_request = "permit_modification_request"
    refused = "refused"
    closed = "closed"
    cancelled = "cancelled"
    revoked = "revoked"
    progressed = "progressed"
    upcoming_enum = "upcoming_enum"
    under_assessment = "under_assessment"


class PermitConditionTypeResponse(Enum):
    NCT01a = "NCT01a"
    NCT01b = "NCT01b"
    NCT02a = "NCT02a"
    NCT02b = "NCT02b"
    NCT04a = "NCT04a"
    NCT04b = "NCT04b"
    NCT05a = "NCT05a"
    NCT06a = "NCT06a"
    NCT07a = "NCT07a"
    NCT08a = "NCT08a"
    NCT08b = "NCT08b"
    NCT09a = "NCT09a"
    NCT09b = "NCT09b"
    NCT09c = "NCT09c"
    NCT10a = "NCT10a"
    NCT11a = "NCT11a"
    NCT11b = "NCT11b"
    NCT12a = "NCT12a"
    upcoming_enum = "upcoming_enum"


class PermitCondition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    condition: PermitConditionTypeResponse
    condition_string: str
    comment: str | None = None


class ActivityTypeResponse(Enum):
    highway_improvement_works = "highway_improvement_works"
    highway_repair_and_maintenance_works = "highway_repair_and_maintenance_works"
    utility_asset_works = "utility_asset_works"
    utility_repair_and_maintenance_works = "utility_repair_and_maintenance_works"
    diversionary_works = "diversionary_works"
    disconnection_or_alteration_of_supply = "disconnection_or_alteration_of_supply"
    permanent_reinstatement = "permanent_reinstatement"
    remedial_works = "remedial_works"
    section_58 = "section_58"
    section_50 = "section_50"
    core_sampling = "core_sampling"
    statutory_infrastructure_works = "statutory_infrastructure_works"
    works_for_rail_purposes = "works_for_rail_purposes"
    works_for_road_purposes = "works_for_road_purposes"
    new_service_connection = "new_service_connection"
    optional_permit_no_fee = "optional_permit_no_fee"
    upcoming_enum = "upcoming_enum"


class PermitSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    promoter_swa_code: str
    promoter_organisation: str
    highway_authority: str
    works_coordinates: Any
    location_description: str
    street: str
    town: str
    area: str
    work_category: WorkCategoryResponse
    work_category_string: str
    description_of_work: str
    traffic_management_type: TrafficManagementTypeResponse
    traffic_management_type_string: str
    assessment_status: AssessmentStatusResponse | None = None
    assessment_status_string: str | None = None
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    actual_start_date: AwareDatetime | None = None
    actual_end_date: AwareDatetime | None = None
    status: PermitStatusResponse
    status_string: str
    work_status: WorkStatusResponse
    work_status_string: str
    deadline_date: AwareDatetime
    date_created: AwareDatetime
    status_changed_date: AwareDatetime
    usrn: float
    is_active_permit: bool
    permit_conditions: list[PermitCondition] | None = None
    road_category: float
    is_traffic_sensitive: bool
    has_no_final_reinstatement: bool
    is_deemed: bool
    excavation_carried_out: bool
    is_early_start: bool
    is_high_impact_traffic_management: bool
    is_lane_rental: bool
    lane_rental_assessment_outcome: LaneRentalAssessmentOutcomeResponse | None = None
    lane_rental_assessment_outcome_string: str | None = None
    lane_rental_charges_not_agreed: bool
    lane_rental_charges_potentially_apply: bool
    paa_to_pa_deadline_date: AwareDatetime | None = None
    activity_type: ActivityTypeResponse
    activity_type_string: str
    reasonable_period_end_date: AwareDatetime | None = None


class PermitReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PermitSummaryResponse]


class PermitStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    permit_modification_request = "permit_modification_request"
    refused = "refused"
    closed = "closed"
    cancelled = "cancelled"
    revoked = "revoked"
    progressed = "progressed"
    under_assessment = "under_assessment"


class PermitSortColumn(Enum):
    date_created = "date_created"
    deadline_date = "deadline_date"
    end_date = "end_date"
    start_date = "start_date"
    status_changed_date = "status_changed_date"
    reasonable_period_end_date = "reasonable_period_end_date"


class PermitDurationChallengeSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    usrn: float
    promoter_swa_code: str
    promoter_organisation: str
    highway_authority: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    actual_start_date: AwareDatetime | None = None
    actual_end_date: AwareDatetime | None = None
    reasonable_period_end_date: AwareDatetime
    assessment_status_changed_date: AwareDatetime
    duration_challenge_review_status: DurationChallengeReviewStatusResponse | None = (
        None
    )
    duration_challenge_review_status_string: str | None = None
    duration_challenge_review_update_date: AwareDatetime | None = None
    duration_challenge_non_acceptance_response_status: (
        DurationChallengeNonAcceptanceResponseStatusResponse | None
    ) = None
    duration_challenge_non_acceptance_response_status_string: str | None = None
    duration_challenge_non_acceptance_response_update_date: AwareDatetime | None = None
    duration_challenge_follow_up_review_complete: bool | None = None
    work_status: WorkStatusResponse
    work_status_string: str


class PermitDurationChallengeReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PermitDurationChallengeSummaryResponse]


class PermitDurationChallengeSortColumn(Enum):
    assessment_status_changed_date = "assessment_status_changed_date"


class ReinstatementsDueSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    organisation_name: str
    street: str
    town: str
    area: str
    work_stopped_date: AwareDatetime
    registration_due_date: AwareDatetime


class ReinstatementsDueReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ReinstatementsDueSummaryResponse]


class FileSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_id: float
    name: str


class FileSummaryReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[FileSummaryResponse]


class FileType(Enum):
    images = "images"
    documents = "documents"


class OffenceCodeResponse(Enum):
    offence_code_05 = "offence_code_05"
    offence_code_06 = "offence_code_06"
    offence_code_08 = "offence_code_08"
    offence_code_09 = "offence_code_09"
    upcoming_enum = "upcoming_enum"


class FPNStatusResponse(Enum):
    issued = "issued"
    accepted = "accepted"
    paid = "paid"
    paid_discounted = "paid_discounted"
    disputed = "disputed"
    withdrawn = "withdrawn"
    upcoming_enum = "upcoming_enum"


class FPNSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fpn_reference_number: str
    work_reference_number: str
    promoter: str
    highway_authority: str
    offence_code: OffenceCodeResponse
    offence_code_string: str
    street_name: str
    issue_date: AwareDatetime
    status: FPNStatusResponse
    status_string: str
    status_changed_date: AwareDatetime


class FPNReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[FPNSummaryResponse]


class FPNStatus(Enum):
    issued = "issued"
    accepted = "accepted"
    paid = "paid"
    paid_discounted = "paid_discounted"
    disputed = "disputed"
    withdrawn = "withdrawn"


class OffenceCode(Enum):
    offence_code_05 = "offence_code_05"
    offence_code_06 = "offence_code_06"
    offence_code_08 = "offence_code_08"
    offence_code_09 = "offence_code_09"


class FPNSortColumn(Enum):
    issue_date_time = "issue_date_time"
    status_changed_date = "status_changed_date"


class CommentTopicResponse(Enum):
    GENERAL = "GENERAL"
    SECTION_74 = "SECTION_74"
    INSPECTION = "INSPECTION"
    FPN = "FPN"
    OVERRUN = "OVERRUN"
    FORWARD_PLAN = "FORWARD_PLAN"
    CHANGE_REQUEST = "CHANGE_REQUEST"
    IMPOSED_VARIATION = "IMPOSED_VARIATION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    SECTION_81 = "SECTION_81"
    UNATTRIBUTED_WORKS = "UNATTRIBUTED_WORKS"
    upcoming_enum = "upcoming_enum"


class CommentSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    topic: CommentTopicResponse
    topic_string: str
    author_email_address: str
    author_organisation_reference: str
    detail: str
    date_created: AwareDatetime
    comment_reference_number: str
    is_read: bool
    read_on: AwareDatetime | None = None
    read_by: str | None = None
    is_internal: bool


class CommentReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[CommentSummaryResponse]


class CommentTopic(Enum):
    GENERAL = "GENERAL"
    SECTION_74 = "SECTION_74"
    INSPECTION = "INSPECTION"
    FPN = "FPN"
    OVERRUN = "OVERRUN"
    FORWARD_PLAN = "FORWARD_PLAN"
    CHANGE_REQUEST = "CHANGE_REQUEST"
    IMPOSED_VARIATION = "IMPOSED_VARIATION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    SECTION_81 = "SECTION_81"
    UNATTRIBUTED_WORKS = "UNATTRIBUTED_WORKS"


class InspectionTypeResponse(Enum):
    live_site = "live_site"
    reinstatement = "reinstatement"
    non_compliance_follow_up = "non_compliance_follow_up"
    section_81 = "section_81"
    investigatory_works = "investigatory_works"
    upcoming_enum = "upcoming_enum"


class InspectionCategoryResponse(Enum):
    a = "a"
    b = "b"
    c = "c"
    third_party = "third_party"
    routine = "routine"
    joint_site_visit = "joint_site_visit"
    follow_up = "follow_up"
    follow_up_completion = "follow_up_completion"
    site_occupancy = "site_occupancy"
    conditions = "conditions"
    core_sample = "core_sample"
    skid_resistance = "skid_resistance"
    texture_depth = "texture_depth"
    surface_regularity = "surface_regularity"
    trial_hole = "trial_hole"
    upcoming_enum = "upcoming_enum"


class InspectionOutcomeResponse(Enum):
    passed = "passed"
    unable_to_complete_inspection = "unable_to_complete_inspection"
    failed_low = "failed_low"
    failed_high = "failed_high"
    further_inspections_required = "further_inspections_required"
    agreed_site_compliance = "agreed_site_compliance"
    non_compliant_with_conditions = "non_compliant_with_conditions"
    works_stopped_apparatus_remaining = "works_stopped_apparatus_remaining"
    works_in_progress_no_carriageway_incursion = (
        "works_in_progress_no_carriageway_incursion"
    )
    works_in_progress = "works_in_progress"
    works_stopped = "works_stopped"
    failed = "failed"
    upcoming_enum = "upcoming_enum"


class InspectionStatusResponse(Enum):
    recorded = "recorded"
    withdrawn = "withdrawn"
    scheduled = "scheduled"
    upcoming_enum = "upcoming_enum"


class InspectionOutcomeStatusTypeResponse(Enum):
    inspection_outcome_accepted = "inspection_outcome_accepted"
    inspection_outcome_disputed = "inspection_outcome_disputed"
    inspection_outcome_promoter_accepts_failed_inspection = (
        "inspection_outcome_promoter_accepts_failed_inspection"
    )
    joint_site_meeting_needed = "joint_site_meeting_needed"
    reviewing_dispute = "reviewing_dispute"
    no_agreement = "no_agreement"
    inspection_withdrawn = "inspection_withdrawn"
    upcoming_enum = "upcoming_enum"


class InspectionSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inspection_date: AwareDatetime
    work_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    inspection_reference_number: str | None = None
    inspection_type: InspectionTypeResponse
    inspection_type_string: str
    inspection_category: InspectionCategoryResponse | None = None
    inspection_category_string: str | None = None
    inspection_outcome: InspectionOutcomeResponse | None = None
    inspection_outcome_string: str | None = None
    inspector_name: str | None = None
    highway_authority: str
    promoter_organisation: str
    made_safe_by_ha: bool | None = None
    date_created: AwareDatetime
    inspection_status: InspectionStatusResponse
    inspection_status_string: str
    date_modified: AwareDatetime
    promoter_response_status: InspectionOutcomeStatusTypeResponse | None = None
    promoter_response_status_string: str | None = None
    ha_response_status: InspectionOutcomeStatusTypeResponse | None = None
    ha_response_status_string: str | None = None
    auto_acceptance_due_date: AwareDatetime | None = None
    is_auto_accepted: bool | None = None


class InspectionReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[InspectionSummaryResponse]


class InspectionType(Enum):
    live_site = "live_site"
    reinstatement = "reinstatement"
    non_compliance_follow_up = "non_compliance_follow_up"
    section_81 = "section_81"
    investigatory_works = "investigatory_works"


class InspectionOutcome(Enum):
    passed = "passed"
    unable_to_complete_inspection = "unable_to_complete_inspection"
    failed_low = "failed_low"
    failed_high = "failed_high"
    further_inspections_required = "further_inspections_required"
    agreed_site_compliance = "agreed_site_compliance"
    non_compliant_with_conditions = "non_compliant_with_conditions"
    works_stopped_apparatus_remaining = "works_stopped_apparatus_remaining"
    works_in_progress_no_carriageway_incursion = (
        "works_in_progress_no_carriageway_incursion"
    )
    works_in_progress = "works_in_progress"
    works_stopped = "works_stopped"
    failed = "failed"


class InspectionSortColumn(Enum):
    inspection_date = "inspection_date"


class InspectionCategory(Enum):
    a = "a"
    b = "b"
    c = "c"
    third_party = "third_party"
    routine = "routine"
    joint_site_visit = "joint_site_visit"
    follow_up = "follow_up"
    follow_up_completion = "follow_up_completion"
    site_occupancy = "site_occupancy"
    conditions = "conditions"
    core_sample = "core_sample"
    skid_resistance = "skid_resistance"
    texture_depth = "texture_depth"
    surface_regularity = "surface_regularity"
    trial_hole = "trial_hole"


class PromoterInspectionOutcomeStatusType(Enum):
    inspection_outcome_accepted = "inspection_outcome_accepted"
    inspection_outcome_disputed = "inspection_outcome_disputed"
    joint_site_meeting_needed = "joint_site_meeting_needed"
    inspection_outcome_promoter_disagrees_with_ha_acceptance_on_behalf = (
        "inspection_outcome_promoter_disagrees_with_ha_acceptance_on_behalf"
    )
    no_response = "no_response"


class HAInspectionOutcomeStatusType(Enum):
    inspection_outcome_promoter_accepts_failed_inspection = (
        "inspection_outcome_promoter_accepts_failed_inspection"
    )
    reviewing_dispute = "reviewing_dispute"
    no_agreement = "no_agreement"
    inspection_withdrawn = "inspection_withdrawn"
    no_response = "no_response"


class WorkstreamStatusResponse(Enum):
    active = "active"
    deactivated = "deactivated"
    upcoming_enum = "upcoming_enum"


class WorkstreamSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prefix: str
    name: str
    description: str | None = None
    status: WorkstreamStatusResponse
    status_string: str
    swa_code: str


class WorkstreamReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[WorkstreamSummaryResponse]


class WorkstreamStatus(Enum):
    active = "active"
    deactivated = "deactivated"


class ReinstatementTypeResponse(Enum):
    excavation = "excavation"
    bar_holes = "bar_holes"
    core_holes = "core_holes"
    pole_testing = "pole_testing"
    upcoming_enum = "upcoming_enum"


class ReinstatementStatusResponse(Enum):
    interim = "interim"
    permanent = "permanent"
    upcoming_enum = "upcoming_enum"


class ReinstatementSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    site_reference_number: str
    work_reference_number: str
    reinstatement_reference_number: str
    promoter_organisation: str
    highway_authority: str
    street_name: str
    town: str | None = None
    area_name: str | None = None
    location_description: str
    registration_date: AwareDatetime
    reinstatement_date: AwareDatetime | None = None
    reinstatement_type: ReinstatementTypeResponse
    reinstatement_type_string: str
    reinstatement_status: ReinstatementStatusResponse
    reinstatement_status_string: str
    end_date: AwareDatetime | None = None
    is_active_reinstatement: bool
    is_subsumed: bool


class ReinstatementReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ReinstatementSummaryResponse]


class ReinstatementSortColumn(Enum):
    end_date = "end_date"


class ReinstatementStatus(Enum):
    interim = "interim"
    permanent = "permanent"


class ForwardPlanStatusResponse(Enum):
    raised = "raised"
    cancelled = "cancelled"
    progressed = "progressed"
    upcoming_enum = "upcoming_enum"


class ForwardPlanSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    forward_plan_reference_number: str
    promoter_organisation: str
    highway_authority: str
    location_description: str
    street: str
    town: str
    area: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    forward_plan_status: ForwardPlanStatusResponse
    forward_plan_status_string: str
    date_created: AwareDatetime


class ForwardPlanReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ForwardPlanSummaryResponse]


class ForwardPlanStatus(Enum):
    raised = "raised"
    cancelled = "cancelled"
    progressed = "progressed"


class ForwardPlanSortColumn(Enum):
    start_date = "start_date"
    end_date = "end_date"


class Section58StatusResponse(Enum):
    proposed = "proposed"
    in_force = "in_force"
    cancelled = "cancelled"
    closed = "closed"
    upcoming_enum = "upcoming_enum"


class Section58DurationResponse(Enum):
    six_months = "six_months"
    one_year = "one_year"
    two_years = "two_years"
    three_years = "three_years"
    upcoming_enum = "upcoming_enum"


class Section58SummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_created: AwareDatetime
    section_58_reference_number: str
    street: str
    town: str | None = None
    area: str | None = None
    section_58_status: Section58StatusResponse
    section_58_status_string: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    restriction_duration: Section58DurationResponse
    restriction_duration_string: str
    usrn: float
    ha_organisation_name: str


class Section58ReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[Section58SummaryResponse]


class Section58Status(Enum):
    proposed = "proposed"
    in_force = "in_force"
    cancelled = "cancelled"
    closed = "closed"


class Section58SortColumn(Enum):
    date_created = "date_created"


class OverrunWarningReasonResponse(Enum):
    more_than_five_slg_items_left_on_site = "more_than_five_slg_items_left_on_site"
    five_or_less_slg_items_left_on_site = "five_or_less_slg_items_left_on_site"
    open_excavation = "open_excavation"
    spoil_left_on_site = "spoil_left_on_site"
    missing_road_markings = "missing_road_markings"
    missing_street_apparatus = "missing_street_apparatus"
    active_traffic_management = "active_traffic_management"
    upcoming_enum = "upcoming_enum"


class Section74HAStatusResponse(Enum):
    warning_issued = "warning_issued"
    charges_ended = "charges_ended"
    warning_disputed = "warning_disputed"
    withdrawn = "withdrawn"
    draft_invoice_issued = "draft_invoice_issued"
    resolved = "resolved"
    upcoming_enum = "upcoming_enum"


class Section74PromoterStatusResponse(Enum):
    acknowledge_overrun_warning = "acknowledge_overrun_warning"
    site_visited_and_rectified = "site_visited_and_rectified"
    warning_disputed = "warning_disputed"
    acknowledge_draft_invoice = "acknowledge_draft_invoice"
    charge_under_review = "charge_under_review"
    charge_agreed = "charge_agreed"
    upcoming_enum = "upcoming_enum"


class Section74SummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    section_74_reference_number: str
    date_created: AwareDatetime
    promoter_organisation_name: str
    ha_organisation_name: str
    location_description: str
    overrun_warning_reasons: list[OverrunWarningReasonResponse]
    overrun_warning_reasons_string: list[str]
    ha_status: Section74HAStatusResponse
    ha_status_string: str
    promoter_status: Section74PromoterStatusResponse | None = None
    promoter_status_string: str | None = None
    latest_ha_response_date: AwareDatetime | None = None


class Section74ReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[Section74SummaryResponse]


class Section74HAStatus(Enum):
    warning_issued = "warning_issued"
    charges_ended = "charges_ended"
    warning_disputed = "warning_disputed"
    withdrawn = "withdrawn"
    draft_invoice_issued = "draft_invoice_issued"
    resolved = "resolved"


class Section74SortColumn(Enum):
    date_created = "date_created"


class Section81SeverityResponse(Enum):
    high = "high"
    low = "low"
    upcoming_enum = "upcoming_enum"


class Section81StatusResponse(Enum):
    issued = "issued"
    acknowledged = "acknowledged"
    accepted = "accepted"
    accepted_fixed = "accepted_fixed"
    rejected = "rejected"
    resolved_by_ha = "resolved_by_ha"
    cancelled = "cancelled"
    reassigned = "reassigned"
    upcoming_enum = "upcoming_enum"


class Section81TypeResponse(Enum):
    tee_valve_access_covers = "tee_valve_access_covers"
    cabinet = "cabinet"
    marker_post = "marker_post"
    pole_post = "pole_post"
    overhead_cables_broken_low_encroaching_onto_highway = (
        "overhead_cables_broken_low_encroaching_onto_highway"
    )
    other = "other"
    unattributed_works_live_site = "unattributed_works_live_site"
    unattributed_works_completed = "unattributed_works_completed"
    upcoming_enum = "upcoming_enum"


class Section81SummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    issue_date: AwareDatetime
    work_reference_number: str
    section_81_reference_number: str
    promoter_organisation: str
    highway_authority: str
    location_description: str
    street: str
    town: str | None = None
    area: str | None = None
    section_81_severity: Section81SeverityResponse | None = None
    section_81_severity_string: str | None = None
    made_safe_by_ha: bool | None = None
    section_81_status: Section81StatusResponse
    section_81_status_string: str
    status_changed_date: AwareDatetime
    section_81_type: Section81TypeResponse
    section_81_type_string: str


class Section81ReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[Section81SummaryResponse]


class Section81Status(Enum):
    issued = "issued"
    acknowledged = "acknowledged"
    accepted = "accepted"
    accepted_fixed = "accepted_fixed"
    rejected = "rejected"
    resolved_by_ha = "resolved_by_ha"
    cancelled = "cancelled"
    reassigned = "reassigned"


class Section81Severity(Enum):
    high = "high"
    low = "low"


class Section81SortColumn(Enum):
    status_changed_date = "status_changed_date"


class Section81Type(Enum):
    tee_valve_access_covers = "tee_valve_access_covers"
    cabinet = "cabinet"
    marker_post = "marker_post"
    pole_post = "pole_post"
    other = "other"
    overhead_cables_broken_low_encroaching_onto_highway = (
        "overhead_cables_broken_low_encroaching_onto_highway"
    )
    unattributed_works_live_site = "unattributed_works_live_site"
    unattributed_works_completed = "unattributed_works_completed"


class RoleResponse(Enum):
    Planner = "Planner"
    HighwayAuthority = "HighwayAuthority"
    Admin = "Admin"
    Contractor = "Contractor"
    API = "API"
    UI = "UI"
    DataExport = "DataExport"
    StreetWorksAdmin = "StreetWorksAdmin"
    upcoming_enum = "upcoming_enum"


class PermissionResponse(Enum):
    Permit = "Permit"
    Compliance = "Compliance"
    Work = "Work"
    upcoming_enum = "upcoming_enum"


class RolePermissionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: RoleResponse
    role_string: str
    permissions: list[PermissionResponse]
    permissions_string: list[str]


class WorkstreamAccessLevelResponse(Enum):
    read_only = "read_only"
    full_write = "full_write"
    upcoming_enum = "upcoming_enum"


class UserWorkstreamAccess(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workstream_prefix: str
    access_level: WorkstreamAccessLevelResponse
    access_level_string: str


class UsersSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_name: str | None = None
    last_name: str | None = None
    email: str
    role_permissions: list[RolePermissionsResponse] | None = None
    workstreams: list[UserWorkstreamAccess] | None = None


class UsersReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[UsersSummaryResponse]


class CSVExportStatusResponse(Enum):
    queued = "queued"
    in_progress = "in_progress"
    ready = "ready"
    failed = "failed"
    upcoming_enum = "upcoming_enum"


class CSVExportTypeResponse(Enum):
    FEE = "FEE"
    FORWARD_PLAN = "FORWARD_PLAN"
    FPN = "FPN"
    INSPECTION = "INSPECTION"
    PERMIT = "PERMIT"
    REINSTATEMENT = "REINSTATEMENT"
    SECTION_81 = "SECTION_81"
    PERMIT_ALTERATION = "PERMIT_ALTERATION"
    ORGANISATION_DATA = "ORGANISATION_DATA"
    COMMENT = "COMMENT"
    REPORTING_INSPECTION_OUTCOMES = "REPORTING_INSPECTION_OUTCOMES"
    REPORTING_PERMITS_CREATED = "REPORTING_PERMITS_CREATED"
    REPORTING_PERMIT_OUTCOMES = "REPORTING_PERMIT_OUTCOMES"
    REPORTING_ALTERATIONS_CREATED = "REPORTING_ALTERATIONS_CREATED"
    REPORTING_ALTERATION_OUTCOMES = "REPORTING_ALTERATION_OUTCOMES"
    REPORTING_FPNS_CREATED = "REPORTING_FPNS_CREATED"
    REPORTING_PERMITS_DEEMED = "REPORTING_PERMITS_DEEMED"
    SECTION_58 = "SECTION_58"
    SECTION_74 = "SECTION_74"
    SAMPLE_INSPECTIONS_DUE = "SAMPLE_INSPECTIONS_DUE"
    EXPIRING_INTERIM_REINSTATEMENT = "EXPIRING_INTERIM_REINSTATEMENT"
    PBI_SAMPLE_INSPECTIONS_DUE = "PBI_SAMPLE_INSPECTIONS_DUE"
    REPORTING_PBI_PASS_FAIL_RATES = "REPORTING_PBI_PASS_FAIL_RATES"
    NUMBER_OF_INSPECTION_UNITS = "NUMBER_OF_INSPECTION_UNITS"
    PRIVATE_STREET_NOTICE = "PRIVATE_STREET_NOTICE"
    REINSPECTION = "REINSPECTION"
    NON_COMPLIANCE = "NON_COMPLIANCE"
    REINSTATEMENTS_DUE = "REINSTATEMENTS_DUE"
    MATERIAL_CLASSIFICATION = "MATERIAL_CLASSIFICATION"
    PBI_SAMPLE_INSPECTION_TARGET = "PBI_SAMPLE_INSPECTION_TARGET"
    INTERESTED_PARTY_PERMIT = "INTERESTED_PARTY_PERMIT"
    CHANGE_REQUEST = "CHANGE_REQUEST"
    upcoming_enum = "upcoming_enum"


class CSVExportSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    csv_export_id: float
    filename: str
    date_created: AwareDatetime
    csv_export_status: CSVExportStatusResponse
    csv_export_status_string: str
    username: str
    csv_export_type: CSVExportTypeResponse
    csv_export_type_string: str
    export_description: str | None = None


class CSVExportReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[CSVExportSummaryResponse]


class GeographicalAreaResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geographical_area_reference_number: str
    area_name: str
    file_id: float
    number_of_usrns: float
    date_modified: AwareDatetime


class PbiSampleInspectionTargetSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pbi_sample_inspection_target_reference_number: str
    organisation_name: str
    org_ref: str
    inspection_units: float
    inspection_rate: float
    target_a: float
    target_b: float
    target_c: float
    completed_a: float
    completed_b: float
    completed_c: float
    generated_b: float
    generated_c: float
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = None
    is_inspection_rate_auto_updated: bool


class PbiSampleInspectionTargetReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PbiSampleInspectionTargetSummaryResponse]


class PbiSampleInspectionTargetSortColumn(Enum):
    is_inspection_rate_auto_updated = "is_inspection_rate_auto_updated"


class PbiSampleInspectionSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pbi_sample_inspection_reference_number: str
    work_reference_number: str
    street: str
    town: str | None = None
    area: str | None = None
    location_description: str
    promoter_organisation: str
    inspection_category: InspectionCategoryResponse
    inspection_category_string: str
    sample_expiry_date: AwareDatetime


class PbiSampleInspectionReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PbiSampleInspectionSummaryResponse]


class PbiSampleInspectionSortColumn(Enum):
    work_end_date = "work_end_date"
    sample_expiry_date = "sample_expiry_date"


class WorkSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    work_status: WorkStatusResponse
    work_status_string: str
    work_start_date: AwareDatetime
    work_end_date: AwareDatetime
    work_start_time: AwareDatetime | None = None
    work_end_time: AwareDatetime | None = None


class WorkSearchReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[WorkSearchResponse]


class ReinspectionSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inspection_date: AwareDatetime
    work_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    inspection_type: InspectionTypeResponse
    inspection_type_string: str
    inspection_category: InspectionCategoryResponse | None = None
    inspection_category_string: str | None = None
    highway_authority: str
    promoter_organisation: str
    date_modified: AwareDatetime


class ReinspectionReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ReinspectionSummaryResponse]


class ReinspectionSortColumn(Enum):
    reinspection_date = "reinspection_date"


class PrivateStreetStatusResponse(Enum):
    cancelled = "cancelled"
    issued = "issued"
    upcoming_enum = "upcoming_enum"


class PrivateStreetSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    private_street_reference_number: str
    works_location_description: str
    promoter_organisation: str
    ha_organisation: str
    work_reference_number: str
    start_date: AwareDatetime
    start_time: AwareDatetime | None = None
    end_date: AwareDatetime
    end_time: AwareDatetime | None = None
    date_created: AwareDatetime
    status: PrivateStreetStatusResponse
    status_string: str


class PrivateStreetReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PrivateStreetSummaryResponse]


class PrivateStreetNoticeSortColumn(Enum):
    date_created = "date_created"
    start_date = "start_date"
    end_date = "end_date"


class PrivateStreetStatus(Enum):
    cancelled = "cancelled"
    issued = "issued"


class NonComplianceStatusResponse(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    resolved = "resolved"
    upcoming_enum = "upcoming_enum"


class NonComplianceResponseStatusResponse(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    works_completed_and_passed = "works_completed_and_passed"
    joint_site_meeting_suggested = "joint_site_meeting_suggested"
    will_attend_joint_site_meeting = "will_attend_joint_site_meeting"
    works_complete_ready_for_inspection = "works_complete_ready_for_inspection"
    joint_site_meeting_not_needed = "joint_site_meeting_not_needed"
    accept_suggestion = "accept_suggestion"
    upcoming_enum = "upcoming_enum"


class NonComplianceSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    non_compliance_reference_number: str
    work_reference_number: str
    promoter_organisation: str
    ha_organisation: str
    date_created: AwareDatetime
    associated_inspections: float
    non_compliance_status: NonComplianceStatusResponse
    non_compliance_status_string: str
    latest_ha_response_status: NonComplianceResponseStatusResponse
    latest_ha_response_status_string: str
    latest_ha_response_date: AwareDatetime
    latest_promoter_response_status: NonComplianceResponseStatusResponse | None = None
    latest_promoter_response_status_string: str | None = None
    latest_promoter_response_date: AwareDatetime | None = None
    street: str
    town: str
    area: str
    most_recent_inspection_type: InspectionTypeResponse
    most_recent_inspection_type_string: str
    most_recent_inspection_outcome: InspectionOutcomeResponse
    most_recent_inspection_outcome_string: str
    most_recent_inspection_promoter_response_status: (
        InspectionOutcomeStatusTypeResponse | None
    ) = None
    most_recent_inspection_promoter_response_status_string: str | None = None
    most_recent_inspection_ha_response_status: (
        InspectionOutcomeStatusTypeResponse | None
    ) = None
    most_recent_inspection_ha_response_status_string: str | None = None


class NonComplianceReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[NonComplianceSummaryResponse]


class NonComplianceStatus(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    resolved = "resolved"


class NonComplianceResponseStatus(Enum):
    issued = "issued"
    withdrawn = "withdrawn"
    works_completed_and_passed = "works_completed_and_passed"
    joint_site_meeting_suggested = "joint_site_meeting_suggested"
    will_attend_joint_site_meeting = "will_attend_joint_site_meeting"
    works_complete_ready_for_inspection = "works_complete_ready_for_inspection"
    joint_site_meeting_not_needed = "joint_site_meeting_not_needed"
    accept_suggestion = "accept_suggestion"
    no_response = "no_response"


class NonComplianceSortColumn(Enum):
    date_created = "date_created"


class MaterialClassificationClassification(Enum):
    hazardous = "hazardous"
    non_hazardous = "non_hazardous"


class HazardousMaterialType(Enum):
    coal_tar = "coal_tar"
    total_petroleum_hydrocarbons = "total_petroleum_hydrocarbons"
    ph = "ph"
    heavy_metal = "heavy_metal"
    asbestos = "asbestos"
    other = "other"


class MaterialClassificationSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_created: AwareDatetime
    sample_date: AwareDatetime
    material_classification_reference_number: str
    street: str
    town: str
    area: str
    usrn: float
    material_classification_classification: MaterialClassificationClassification
    hazardous_material_types: list[HazardousMaterialType] | None = None
    hazardous_material_type_other_description: str | None = None


class MaterialClassificationReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[MaterialClassificationSummaryResponse]


class AsyncJobStatusResponse(Enum):
    queued = "queued"
    in_progress = "in_progress"
    complete = "complete"
    failed = "failed"
    upcoming_enum = "upcoming_enum"


class PbiSampleGenerationJobsSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date_created: AwareDatetime
    async_job_status: AsyncJobStatusResponse
    async_job_status_string: str
    username: str


class PbiSampleGenerationJobsReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[PbiSampleGenerationJobsSummaryResponse]


class ChangeRequestStatusResponse(Enum):
    submitted = "submitted"
    granted = "granted"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    revoked = "revoked"
    auto_applied = "auto_applied"
    upcoming_enum = "upcoming_enum"


class ChangeRequestTypeResponse(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"
    upcoming_enum = "upcoming_enum"


class ChangeRequestSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    change_request_reference_number: str
    street: str
    town: str
    area: str
    location_description: str
    highway_authority: str
    promoter: str
    work_category: WorkCategoryResponse
    work_category_string: str
    change_request_status: ChangeRequestStatusResponse
    change_request_status_string: str
    change_request_type: ChangeRequestTypeResponse
    change_request_type_string: str
    date_created: AwareDatetime
    deadline_date: AwareDatetime
    status_changed_date: AwareDatetime


class ChangeRequestReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ChangeRequestSummaryResponse]


class ChangeRequestStatus(Enum):
    submitted = "submitted"
    granted = "granted"
    refused = "refused"
    deemed = "deemed"
    cancelled = "cancelled"
    granted_with_duration_challenge = "granted_with_duration_challenge"
    revoked = "revoked"
    auto_applied = "auto_applied"


class ChangeRequestType(Enum):
    PROMOTER_IMPOSED_CHANGE = "PROMOTER_IMPOSED_CHANGE"
    PROMOTER_CHANGE_REQUEST = "PROMOTER_CHANGE_REQUEST"
    HA_CHANGE_REQUEST = "HA_CHANGE_REQUEST"
    HA_IMPOSED_CHANGE = "HA_IMPOSED_CHANGE"
    WORK_EXTENSION = "WORK_EXTENSION"
    DURATION_CHALLENGE = "DURATION_CHALLENGE"
    MODIFIED_PERMIT = "MODIFIED_PERMIT"


class ChangeRequestSortColumn(Enum):
    date_created = "date_created"
    deadline_date = "deadline_date"


class ChangeRequestDurationChallengeSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    change_request_reference_number: str
    location_description: str
    street: str
    town: str
    area: str
    usrn: float
    promoter_swa_code: str
    promoter_organisation: str
    highway_authority: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    proposed_start_time: AwareDatetime | None = None
    proposed_end_time: AwareDatetime | None = None
    actual_start_date: AwareDatetime | None = None
    actual_end_date: AwareDatetime | None = None
    reasonable_period_end_date: AwareDatetime
    status_changed_date: AwareDatetime
    duration_challenge_review_status: DurationChallengeReviewStatusResponse | None = (
        None
    )
    duration_challenge_review_status_string: str | None = None
    duration_challenge_review_update_date: AwareDatetime | None = None
    duration_challenge_non_acceptance_response_status: (
        DurationChallengeNonAcceptanceResponseStatusResponse | None
    ) = None
    duration_challenge_non_acceptance_response_status_string: str | None = None
    duration_challenge_non_acceptance_response_update_date: AwareDatetime | None = None
    duration_challenge_follow_up_review_complete: bool | None = None
    work_status: WorkStatusResponse
    work_status_string: str


class ChangeRequestDurationChallengeReportingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pagination: PaginationResponse
    rows: list[ChangeRequestDurationChallengeSummaryResponse]


class ChangeRequestDurationChallengeSortColumn(Enum):
    status_changed_date = "status_changed_date"
