"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager sampling API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/sampling/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmp98ztftqn.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SampleInspectionQuotaResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quota: float


class GenerateSampleInspectionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sample_inspection_rate: float = Field(
        ...,
        description="See API specification Resource Guide > Sampling API > Sample inspections for more information",
    )


class SampleInspectionTargetCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sample_inspection_target_reference_number: str


class AnnualInspectionUnitsSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    financial_year_start_date: AwareDatetime
    annual_inspection_units: float | None = None
    is_auto_calculated: bool


class SampleInspectionTargetCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(None, description="Max length 50 characters")
    inspection_units_baseline: float | None = Field(
        None,
        description="Required if annual_inspection_units not provided\nMust be whole number",
    )
    annual_inspection_units: list[AnnualInspectionUnitsSummary] | None = Field(
        None, description="Required if inspection_units_baseline not provided"
    )
    inspection_rate: float = Field(..., description="Must be between 20 and 100")
    target_a: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )
    target_b: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )
    target_c: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )
    promoter_org_ref: str = Field(..., description="Max length 4 characters")


class SampleInspectionTargetUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(None, description="Max length 50 characters")
    inspection_units_baseline: float | None = Field(
        None,
        description="Required if annual_inspection_units not provided\nMust be whole number",
    )
    annual_inspection_units: list[AnnualInspectionUnitsSummary] | None = Field(
        None, description="Required if inspection_units_baseline not provided"
    )
    inspection_rate: float = Field(..., description="Must be between 20 and 100")
    target_a: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )
    target_b: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )
    target_c: float = Field(
        ...,
        description="Sum of target_a + target_b + target_c must not exceed the quarterly quota\nMust be whole number\nSee API specification Resource Guide > Sampling API > Sample inspection quota for more information",
    )


class SampleInspectionTargetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sample_inspection_target_reference_number: str
    org_ref: str
    organisation_name: str
    yearly_inspection_units: float
    inspection_rate: float
    target_a: float
    target_b: float
    target_c: float
    completed_a: float
    completed_b: float
    completed_c: float
    generated_b: float
    generated_c: float


class SampleInspectionStartQuarterRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    internal_user_identifier: str | None = Field(
        None, description="Max length 100 characters"
    )
    internal_user_name: str | None = Field(None, description="Max length 50 characters")
    start_date: AwareDatetime = Field(
        ..., description="Must be a valid financial quarter start date"
    )


class AnnualInspectionUnitsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    annual_inspection_units: list[AnnualInspectionUnitsSummary]
