"""GENERATED FILE - do not edit by hand.

Generated from the DfT Street Manager worklist API swagger specification
(https://api.sandbox.manage-roadworks.service.gov.uk/v6/worklist/swagger.json) by scripts/generate_models.py using datamodel-code-generator.
"""

# generated by datamodel-codegen:
#   filename:  tmplrewneui.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class ChangeRequestsAboutToDeemResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    change_request_reference_number: str
    works_location: str
    promoter: str
    deem_date: AwareDatetime
    change_submission_date: AwareDatetime
    works_category: str
    work_status: str
    start_date: AwareDatetime
    end_date: AwareDatetime


class PermitsAboutToDeemResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    works_location: str
    promoter: str
    deem_date: AwareDatetime
    application_submission_date: AwareDatetime
    works_category: str
    highest_traffic_management_type: str
    start_date: AwareDatetime
    end_date: AwareDatetime


class PotentialWorksOverrunningResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    works_location: str
    promoter: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    reasonable_period_end_date: AwareDatetime


class RefusedPermitsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    works_location: str
    highway_authority: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    refused_date: AwareDatetime
    reasons_for_refusal: list[str]


class WorkStartsDueResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    works_location: str
    highway_authority: str
    proposed_start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    validity_period_end_date: AwareDatetime
    workstream_prefix: str


class WorkStopsDueResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    work_reference_number: str
    permit_reference_number: str
    works_location: str
    highway_authority: str
    start_date: AwareDatetime
    proposed_end_date: AwareDatetime
    reasonable_period_end_date: AwareDatetime
    workstream_prefix: str
