"""GENERATED FILE - do not edit by hand.

D-TRO data-model Pydantic models for schema v3_5_1, generated from
dtro-schema.json by scripts/generate_dtro_models.py.

Formatted strings (email/uri/date/date-time) are plain ``str`` for
lenient, dependency-free validation. Cross-field conditional rules from
the schema are enforced by the D-TRO service on submission, not here.
"""

# generated by datamodel-codegen:
#   filename:  dtro-schema.json

from __future__ import annotations

from enum import Enum, IntEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AccessConditionType(Enum):
    """
    Indicates access restriction type.
    """

    accessOnly = "accessOnly"
    destinationTraffic = "destinationTraffic"
    loadingAndUnloading = "loadingAndUnloading"
    passengerLoadingAndUnloading = "passengerLoadingAndUnloading"
    sourceAndDestinationTraffic = "sourceAndDestinationTraffic"
    sourceTraffic = "sourceTraffic"
    throughTraffic = "throughTraffic"


class ProvisionActionType(Enum):
    """
    Indicates the nature of update between D-TRO records or their constituent parts
    """

    amendment = "amendment"
    errorFix = "errorFix"
    fullAmendment = "fullAmendment"
    fullRevoke = "fullRevoke"
    new = "new"
    noChange = "noChange"
    partialAmendment = "partialAmendment"
    partialRevoke = "partialRevoke"
    informationUpdate = "informationUpdate"


class SourceActionType(Enum):
    amendment = "amendment"
    errorFix = "errorFix"
    new = "new"
    noChange = "noChange"
    informationUpdate = "informationUpdate"


class Authority(BaseModel):
    """
    Object indicating the authority issuing permits
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ..., description="Name of the authority issuing permits", min_length=1
    )


class BywayType(Enum):
    """
    Indicates the nature byways
    """

    footpath = "footpath"
    road = "road"
    bridleway = "bridleway"
    cycleTrack = "cycleTrack"
    restrictedByway = "restrictedByway"
    bywayOpenToAllTraffic = "bywayOpenToAllTraffic"


class CalendarWeekInMonthType(Enum):
    """
    Specification of periods defined by relevant calendar weeks in a month, see ISO 8601-1.
    """

    fifthWeekOfMonth = "fifthWeekOfMonth"
    firstWeekOfMonth = "firstWeekOfMonth"
    fourthWeekOfMonth = "fourthWeekOfMonth"
    secondWeekOfMonth = "secondWeekOfMonth"
    sixthWeekOfMonth = "sixthWeekOfMonth"
    thirdWeekOfMonth = "thirdWeekOfMonth"


class ChangeableTimeType(Enum):
    """
    List of available changeable time types
    """

    dawn = "dawn"
    dusk = "dusk"
    external = "external"
    holiday = "holiday"


class ComparisonOperatorType(Enum):
    """
    The operator to be used in the vehicle characteristic comparison operation.
    """

    equalTo = "equalTo"
    greaterThan = "greaterThan"
    greaterThanOrEqualTo = "greaterThanOrEqualTo"
    lessThan = "lessThan"
    lessThanOrEqualTo = "lessThanOrEqualTo"


class AccessCondition1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accessConditionType: list[AccessConditionType] = Field(..., min_length=1)
    otherAccessRestriction: str | None = Field(None, min_length=1)


class Authority1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., min_length=1)


class CurrencyType(Enum):
    """
    ISO 4217 currency codes (UK subset).
    """

    EUR = "EUR"
    GBP = "GBP"


class DayWithinMonth(RootModel[int]):
    root: int = Field(..., ge=1, le=31)


class DayType(Enum):
    """
    A list of days of the week
    """

    friday = "friday"
    monday = "monday"
    saturday = "saturday"
    sunday = "sunday"
    thursday = "thursday"
    tuesday = "tuesday"
    wednesday = "wednesday"


class DiversionRouteType(Enum):
    """
    Indicates the nature of diversion route
    """

    hgvRoute = "hgvRoute"
    allTraffic = "allTraffic"
    non_HGVRoute = "non-HGVRoute"


class DiversionType(BaseModel):
    """
    An object linking to different forms of diversion route.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    diversionType: DiversionRouteType


class DriverCharacteristicsType(Enum):
    """
    Indicates a specific type of driver characteristic
    """

    disabledWithPermit = "disabledWithPermit"
    hotelGuest = "hotelGuest"
    learnerDriver = "learnerDriver"
    localResident = "localResident"


class DriverCondition9(BaseModel):
    """
    Object indicating condition related to driver characteristics
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    driverCharacteristics: DriverCharacteristicsType


class ElectricChargingCharacteristic1(BaseModel):
    """
    Electric charging characteristics of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    charging: bool = Field(
        ..., description="That the connected vehicle is currently being charged."
    )
    vehicleConnectedToCharger: bool | None = Field(
        None, description="That the vehicle is connected to charging infrastructure."
    )


class ElectricChargingCharacteristic2(BaseModel):
    """
    Electric charging characteristics of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    charging: bool | None = Field(
        None, description="That the connected vehicle is currently being charged."
    )
    vehicleConnectedToCharger: bool = Field(
        ..., description="That the vehicle is connected to charging infrastructure."
    )


class ElectricChargingCharacteristic(
    RootModel[ElectricChargingCharacteristic1 | ElectricChargingCharacteristic2]
):
    root: ElectricChargingCharacteristic1 | ElectricChargingCharacteristic2 = Field(
        ..., description="Electric charging characteristics of a vehicle."
    )


class EmissionClassificationEuroType(Enum):
    """
    The minimum Euro emission classification.
    """

    euro5 = "euro5"
    euro5a = "euro5a"
    euro5b = "euro5b"
    euro6 = "euro6"
    euro6a = "euro6a"
    euro6b = "euro6b"
    euro6c = "euro6c"
    euroV = "euroV"
    euroVI = "euroVI"
    other = "other"


class EventType(Enum):
    """
    Indicates that the event represents an actual start or stop time
    """

    start = "start"
    stop = "stop"


class ExperimentalCessation(BaseModel):
    """
    Experimental Order cessation.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    actualDateOfCessation: str = Field(
        ..., description="Date the Experimental Order was ceased"
    )
    natureOfCessation: str = Field(..., description="Reason for the cessation")


class ExperimentalVariation(BaseModel):
    """
    Experimental Order variation.
    """

    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    effectOfChange: str = Field(..., description="Effect of the change", min_length=1)
    expectedDuration: str = Field(
        ...,
        description="Duration of the change",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )


class FuelType(Enum):
    """
    List of fuel types
    """

    all = "all"
    battery = "battery"
    biodiesel = "biodiesel"
    cng = "cng"
    diesel = "diesel"
    dieselBatteryHybrid = "dieselBatteryHybrid"
    electric = "electric"
    ethanol = "ethanol"
    fuelCell = "fuelCell"
    hydrogen = "hydrogen"
    liquidGas = "liquidGas"
    lpg = "lpg"
    methane = "methane"
    ng = "ng"
    other = "other"
    petrol = "petrol"
    petrol95Octane = "petrol95Octane"
    petrol98Octane = "petrol98Octane"
    petrolBatteryHybrid = "petrolBatteryHybrid"
    petrolLeaded = "petrolLeaded"
    petrolUnleaded = "petrolUnleaded"
    phev = "phev"
    reev = "reev"
    unknown = "unknown"


class HeaviestAxleWeightCharacteristic(BaseModel):
    """
    Heaviest axle of vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    heaviestAxleWeight: float = Field(
        ..., description="Metric tonnes, one decimal place", ge=0.0
    )


class InstanceOfDayInMonth(Enum):
    """
    Instance of a specific weekday within a month.
    """

    fifthInstance = "fifthInstance"
    firstInstance = "firstInstance"
    fourthInstance = "fourthInstance"
    secondInstance = "secondInstance"
    thirdInstance = "thirdInstance"


class LinearDirectionType(Enum):
    """
    Applicable direction for a linear direction
    """

    bidirectional = "bidirectional"
    endToStart = "endToStart"
    startToEnd = "startToEnd"


class LinearLateralPositionType(Enum):
    """
    Lateral positions
    """

    centreline = "centreline"
    far = "far"
    near = "near"
    onKerb = "onKerb"


class LinearType(Enum):
    """
    Representations derived from a linear location
    """

    linear = "linear"
    representingZone = "representingZone"


class MaximumHeightCharacteristic(BaseModel):
    """
    Height characteristic of a vehicle
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vehicleHeight: float = Field(
        ..., description="Metres, two decimal places.", ge=0.0, multiple_of=0.01
    )


class MaximumLengthCharacteristic(BaseModel):
    """
    Length characteristic of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vehicleLength: float = Field(..., description="Metres, two decimal places.", ge=0.0)


class MaximumWidthCharacteristic(BaseModel):
    """
    Width characteristic of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vehicleWidth: float = Field(..., description="Metres, two decimal places.", ge=0.0)


class MaxStayNoReturn1(BaseModel):
    """
    Max duration for occupancy and minimum time to return.
    """

    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    maximumOccupancy: str = Field(
        ...,
        description="The maximum occupancy duration permitted",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )
    minimumPeriodForReturn: str | None = Field(
        None,
        description="Minimum time between occupancies",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )


class MaxStayNoReturn2(BaseModel):
    """
    Max duration for occupancy and minimum time to return.
    """

    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    maximumOccupancy: str | None = Field(
        None,
        description="The maximum occupancy duration permitted",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )
    minimumPeriodForReturn: str = Field(
        ...,
        description="Minimum time between occupancies",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )


class MaxStayNoReturn(RootModel[MaxStayNoReturn1 | MaxStayNoReturn2]):
    root: MaxStayNoReturn1 | MaxStayNoReturn2 = Field(
        ..., description="Max duration for occupancy and minimum time to return."
    )


class MonthType(Enum):
    """
    List containing calendar months
    """

    april = "april"
    august = "august"
    december = "december"
    february = "february"
    january = "january"
    july = "july"
    june = "june"
    march = "march"
    may = "may"
    november = "november"
    october = "october"
    september = "september"


class NonVehicularRoadUserType(Enum):
    """
    Non-vehicular road user types
    """

    cattleDrive = "cattleDrive"
    herdedAnimals = "herdedAnimals"
    pedestrians = "pedestrians"
    riddenOrAccompaniedHorses = "riddenOrAccompaniedHorses"


class NumberOfAxlesCharacteristic(BaseModel):
    """
    Number of axles characteristic of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    numberOfAxles: int = Field(..., description="Total number of axles.", ge=1)
    comparisonOperator: ComparisonOperatorType


class NumberOfOccupants(BaseModel):
    """
    Conditional restrictions based on number of vehicle occupants
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    operator: ComparisonOperatorType
    value: int = Field(..., description="Number of occupants.")


class OccupantCondition(BaseModel):
    """
    Specific vehicle occupant condition restrictions
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    disabledWithPermit: bool | None = Field(
        None, description="Registered disabled permit holder"
    )
    numberOfOccupants: list[NumberOfOccupants] | None = Field(None, max_length=2)


class LegislationCrossReferenceItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class OffListRegulation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legislationCrossReference: list[LegislationCrossReferenceItem] | None = Field(
        None, min_length=1
    )
    regulationFullText: str = Field(..., min_length=1)
    regulationShortName: str = Field(..., min_length=1)


class OrderReportingPointType(Enum):
    """
    Nature of the traffic regulation measure process Reporting Point.
    """

    experimentalAmendment = "experimentalAmendment"
    experimentalMakingPermanent = "experimentalMakingPermanent"
    experimentalNoticeOfMaking = "experimentalNoticeOfMaking"
    experimentalRevocation = "experimentalRevocation"
    permanentAmendment = "permanentAmendment"
    permanentNoticeOfMaking = "permanentNoticeOfMaking"
    permanentNoticeOfProposal = "permanentNoticeOfProposal"
    permanentRevocation = "permanentRevocation"
    specialEventOrderNoticeOfMaking = "specialEventOrderNoticeOfMaking"
    troOnRoadActiveStatus = "troOnRoadActiveStatus"
    ttroTtmoByNotice = "ttroTtmoByNotice"
    ttroTtmoExtension = "ttroTtmoExtension"
    ttroTtmoNoticeAfterMaking = "ttroTtmoNoticeAfterMaking"
    ttroTtmoNoticeOfIntention = "ttroTtmoNoticeOfIntention"
    ttroTtmoRevocation = "ttroTtmoRevocation"
    variationByNotice = "variationByNotice"


class OtherCondition(BaseModel):
    """
    any other specified conditions or exceptions
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    otherConditionDescription: str = Field(..., min_length=1)


class PayloadType(Enum):
    """
    The type of load carried by the vehicle.
    """

    dangerousGoods = "dangerousGoods"
    empty = "empty"
    explosiveMaterials = "explosiveMaterials"
    other = "other"


class PermitSubjectToFee(BaseModel):
    """
    Cost and restrictions relating to use of a permit
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    amountDue: float | None = Field(
        None, description="Pounds Sterling, two decimal places."
    )
    paymentInformation: str | None = Field(
        None, description="URL for further information."
    )


class PermitType(Enum):
    """
    The type of the referenced permit
    """

    business = "business"
    doctor = "doctor"
    other = "other"
    resident = "resident"
    residentExcludesNonResidentBlueBadge = "residentExcludesNonResidentBlueBadge"
    residentNotBlueBadgeHolders = "residentNotBlueBadgeHolders"
    residentPlusBadgeHolders = "residentPlusBadgeHolders"
    residentWithNonResidentBlueBadge = "residentWithNonResidentBlueBadge"


class PointType(Enum):
    """
    Representations derived from a point location
    """

    centreLinePoint = "centreLinePoint"
    other = "other"
    trafficSignLocation = "trafficSignLocation"


class PublicEventType(Enum):
    """
    List of public event types
    """

    agriculturalShow = "agriculturalShow"
    airShow = "airShow"
    artEvent = "artEvent"
    athleticsMeeting = "athleticsMeeting"
    ballGame = "ballGame"
    baseballGame = "baseballGame"
    basketballGame = "basketballGame"
    beerFestival = "beerFestival"
    bicycleRace = "bicycleRace"
    boatRace = "boatRace"
    boatShow = "boatShow"
    boxingTournament = "boxingTournament"
    bullFight = "bullFight"
    ceremonialEvent = "ceremonialEvent"
    commercialEvent = "commercialEvent"
    concert = "concert"
    cricketMatch = "cricketMatch"
    culturalEvent = "culturalEvent"
    exhibition = "exhibition"
    fair = "fair"
    festival = "festival"
    filmFestival = "filmFestival"
    filmTVMaking = "filmTVMaking"
    fireworkDisplay = "fireworkDisplay"
    flowerEvent = "flowerEvent"
    foodFestival = "foodFestival"
    footballMatch = "footballMatch"
    funfair = "funfair"
    gardeningOrFlowerShow = "gardeningOrFlowerShow"
    golfTournament = "golfTournament"
    hockeyGame = "hockeyGame"
    horseRaceMeeting = "horseRaceMeeting"
    internationalSportsMeeting = "internationalSportsMeeting"
    majorEvent = "majorEvent"
    marathon = "marathon"
    market = "market"
    match = "match"
    motorShow = "motorShow"
    motorSportRaceMeeting = "motorSportRaceMeeting"
    openAirConcert = "openAirConcert"
    other = "other"
    parade = "parade"
    procession = "procession"
    raceMeeting = "raceMeeting"
    rugbyMatch = "rugbyMatch"
    severalMajorEvents = "severalMajorEvents"
    show = "show"
    showJumping = "showJumping"
    soundAndLightShow = "soundAndLightShow"
    sportsMeeting = "sportsMeeting"
    stateOccasion = "stateOccasion"
    streetFestival = "streetFestival"
    tennisTournament = "tennisTournament"
    theatricalEvent = "theatricalEvent"
    tournament = "tournament"
    tradeFair = "tradeFair"
    unknown = "unknown"
    waterSportsMeeting = "waterSportsMeeting"
    wineFestival = "wineFestival"
    winterSportsMeeting = "winterSportsMeeting"


class RateLineType(Enum):
    """
    List of rate line types
    """

    flatRate = "flatRate"
    flatRateTier = "flatRateTier"
    incrementingRate = "incrementingRate"
    perUnit = "perUnit"


class RateType(Enum):
    """
    List of rate types
    """

    daily = "daily"
    hourly = "hourly"


class RateUsageConditionsType(Enum):
    """
    List of rate usage condition types
    """

    fixedDuration = "fixedDuration"
    fixedNumber = "fixedNumber"
    once = "once"
    unlimited = "unlimited"


class RegulatedPlaceType(Enum):
    """
    Nature of RegulatedPlace.
    """

    diversionRoute = "diversionRoute"
    regulationLocation = "regulationLocation"


class RegulationType(Enum):
    bannedMovementNoEntry = "bannedMovementNoEntry"
    bannedMovementNoLeftTurn = "bannedMovementNoLeftTurn"
    bannedMovementNoRightTurn = "bannedMovementNoRightTurn"
    bannedMovementNoUTurn = "bannedMovementNoUTurn"
    dimensionMaximumHeightStructural = "dimensionMaximumHeightStructural"
    dimensionMaximumHeightWithTRO = "dimensionMaximumHeightWithTRO"
    dimensionMaximumLength = "dimensionMaximumLength"
    dimensionMaximumWeightEnvironmental = "dimensionMaximumWeightEnvironmental"
    dimensionMaximumWeightStructural = "dimensionMaximumWeightStructural"
    dimensionMaximumWidth = "dimensionMaximumWidth"
    kerbsideControlledParkingZone = "kerbsideControlledParkingZone"
    kerbsideDisabledBadgeHoldersOnly = "kerbsideDisabledBadgeHoldersOnly"
    kerbsideDoubleRedLines = "kerbsideDoubleRedLines"
    kerbsideFootwayParking = "kerbsideFootwayParking"
    kerbsideFootwayParkingProhibited = "kerbsideFootwayParkingProhibited"
    kerbsideLimitedWaiting = "kerbsideLimitedWaiting"
    kerbsideLoadingBay = "kerbsideLoadingBay"
    kerbsideLoadingBayPassengerSetDownPermitted = (
        "kerbsideLoadingBayPassengerSetDownPermitted"
    )
    kerbsideLoadingBayPassengerSetDownProhibited = (
        "kerbsideLoadingBayPassengerSetDownProhibited"
    )
    kerbsideLoadingPlace = "kerbsideLoadingPlace"
    kerbsideLoadingPlacePassengerSetDownPermitted = (
        "kerbsideLoadingPlacePassengerSetDownPermitted"
    )
    kerbsideLoadingPlacePassengerSetDownProhibited = (
        "kerbsideLoadingPlacePassengerSetDownProhibited"
    )
    kerbsideNoLoadingPassengerSetDownPermitted = (
        "kerbsideNoLoadingPassengerSetDownPermitted"
    )
    kerbsideNoLoadingPassengerSetDownProhibited = (
        "kerbsideNoLoadingPassengerSetDownProhibited"
    )
    kerbsideMotorcycleParkingPlace = "kerbsideMotorcycleParkingPlace"
    kerbsideNoLoading = "kerbsideNoLoading"
    kerbsideNoStopping = "kerbsideNoStopping"
    kerbsideNoWaiting = "kerbsideNoWaiting"
    kerbsideOtherYellowZigZagMandatory = "kerbsideOtherYellowZigZagMandatory"
    kerbsideParkingPlace = "kerbsideParkingPlace"
    kerbsidePaymentParkingPlace = "kerbsidePaymentParkingPlace"
    kerbsidePermitParkingArea = "kerbsidePermitParkingArea"
    kerbsidePermitParkingPlace = "kerbsidePermitParkingPlace"
    kerbsideRedRouteClearway = "kerbsideRedRouteClearway"
    kerbsideRestrictedParkingZone = "kerbsideRestrictedParkingZone"
    kerbsideRedRouteBusStopClearway = "kerbsideRedRouteBusStopClearway"
    kerbsideRuralClearway = "kerbsideRuralClearway"
    kerbsideSchoolKeepClearYellowZigZagMandatory = (
        "kerbsideSchoolKeepClearYellowZigZagMandatory"
    )
    kerbsideSingleRedLines = "kerbsideSingleRedLines"
    kerbsideTaxiRank = "kerbsideTaxiRank"
    kerbsideUrbanClearway = "kerbsideUrbanClearway"
    mandatoryDirectionAheadOnly = "mandatoryDirectionAheadOnly"
    mandatoryDirectionLeftTurnOnly = "mandatoryDirectionLeftTurnOnly"
    mandatoryDirectionOneWay = "mandatoryDirectionOneWay"
    mandatoryDirectionRightTurnOnly = "mandatoryDirectionRightTurnOnly"
    miscBaySuspension = "miscBaySuspension"
    miscBusGate = "miscBusGate"
    miscBusLaneWithTrafficFlow = "miscBusLaneWithTrafficFlow"
    miscBusOnlyStreet = "miscBusOnlyStreet"
    miscCongestionLowEmissionZone = "miscCongestionLowEmissionZone"
    miscContraflow = "miscContraflow"
    miscContraflowBusLane = "miscContraflowBusLane"
    miscCycleHireParking = "miscCycleHireParking"
    miscCycleLane = "miscCycleLane"
    miscCycleLaneClosure = "miscCycleLaneClosure"
    miscCycleParking = "miscCycleParking"
    miscFootpathClosure = "miscFootpathClosure"
    miscFootwayClosure = "miscFootwayClosure"
    miscLaneClosure = "miscLaneClosure"
    miscPROWClosure = "miscPROWClosure"
    miscPedestrianZone = "miscPedestrianZone"
    miscRoadClosure = "miscRoadClosure"
    miscRoadClosureCrossingPoint = "miscRoadClosureCrossingPoint"
    miscSuspensionOfBusway = "miscSuspensionOfBusway"
    miscSuspensionOfOneWay = "miscSuspensionOfOneWay"
    miscSuspensionOfParkingRestriction = "miscSuspensionOfParkingRestriction"
    miscSuspensionOfWeightRestriction = "miscSuspensionOfWeightRestriction"
    miscTemporaryParkingBay = "miscTemporaryParkingBay"
    miscTemporaryParkingRestriction = "miscTemporaryParkingRestriction"
    movementOrderNoOvertaking = "movementOrderNoOvertaking"
    movementOrderPriorityOverOncomingTraffic = (
        "movementOrderPriorityOverOncomingTraffic"
    )
    movementOrderProhibitedAccess = "movementOrderProhibitedAccess"
    nonOrderKerbsideBusStop = "nonOrderKerbsideBusStop"
    nonOrderKerbsidePedestrianCrossing = "nonOrderKerbsidePedestrianCrossing"
    nonOrderMovementBoxJunction = "nonOrderMovementBoxJunction"


class RoadType(Enum):
    """
    List of road types
    """

    aRoad = "aRoad"
    bRoad = "bRoad"
    cRoad = "cRoad"
    motorway = "motorway"
    other = "other"
    trunkRoad = "trunkRoad"


class TraAffectedItem(RootModel[int]):
    root: int = Field(..., ge=1)


class SpecialDayType(Enum):
    """
    Collection of special types of days.
    """

    easter = "easter"
    eventDay = "eventDay"
    goodFriday = "goodFriday"
    marketDay = "marketDay"
    matchDay = "matchDay"
    nonSchoolDay = "nonSchoolDay"
    other = "other"
    publicHoliday = "publicHoliday"
    schoolDay = "schoolDay"


class SpeedLimitNatureType(Enum):
    """
    type of speed limit value indicated
    """

    permanent = "permanent"
    temporary = "temporary"


class SpeedLimitProfileType(Enum):
    """
    List of speed limit profiles
    """

    nationalSpeedLimitDualCarriageway = "nationalSpeedLimitDualCarriageway"
    nationalSpeedLimitMotorway = "nationalSpeedLimitMotorway"
    nationalSpeedLimitSingleCarriageway = "nationalSpeedLimitSingleCarriageway"
    nationalSpeedLimit = "nationalSpeedLimit"


class MphValue(IntEnum):
    integer_10 = 10
    integer_20 = 20
    integer_30 = 30
    integer_40 = 40
    integer_50 = 50
    integer_60 = 60
    integer_70 = 70


class SpeedLimitValueType(Enum):
    """
    List of speed limit value types
    """

    maximumSpeedLimit = "maximumSpeedLimit"
    minimumSpeedLimit = "minimumSpeedLimit"
    nationalSpeedLimitWellLitStreetDefault = "nationalSpeedLimitWellLitStreetDefault"


class TargetEnumeratedList(Enum):
    """
    List of enumeration lists that may be extended
    """

    permitType = "permitType"
    payloadType = "payloadType"
    vehicleUsageType = "vehicleUsageType"
    emissionsClassificationEuroType = "emissionsClassificationEuroType"
    fuelType = "fuelType"
    vehicleEquipmentType = "vehicleEquipmentType"
    vehicleType = "vehicleType"


class TemporaryOverriddenProvision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reference: str = Field(..., min_length=1)


class TemporaryProvision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    temporaryOverriddenProvision: TemporaryOverriddenProvision | None = None


class UniqueStreetReferenceNumber(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nsgStreetName: str | None = Field(None, min_length=1)
    nsgStreetNumber: str | None = Field(None, min_length=1)
    usrn: int = Field(..., ge=0, le=99999999)


class UnitOfMeasureEnum(Enum):
    """
    Defines the unit used for the measure.
    """

    cubicCentimetres = "cubicCentimetres"
    year = "year"
    gkm = "gkm"
    kWh = "kWh"
    eurolevel = "eurolevel"


class ValueRangeBoundary(BaseModel):
    """
    Object defining a range boundary value and operator.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comparisonOperator: ComparisonOperatorType
    value: float = Field(
        ...,
        description="The quantity measure forming a measure boundary.",
        ge=0.0,
        multiple_of=0.01,
    )


class ValueRangeClassEnum(Enum):
    """
    Typifies the type of measured value.
    """

    batteryCapacity = "batteryCapacity"
    engineCapacityPetrol = "engineCapacityPetrol"
    emissionStandard = "emissionStandard"
    engineCapacityDiesel = "engineCapacityDiesel"
    manufactureDate = "manufactureDate"
    emissionValue = "emissionValue"


class VehicleEquipmentType(Enum):
    """
    The type of equipment in use or on board the vehicle.
    """

    dippedHeadlightsInUse = "dippedHeadlightsInUse"
    electronicTollEquipment = "electronicTollEquipment"
    filterInUse = "filterInUse"
    notUsingSnowChains = "notUsingSnowChains"
    notUsingSnowChainsOrTyres = "notUsingSnowChainsOrTyres"
    other = "other"
    snowChainsInUse = "snowChainsInUse"
    snowChainsOrTyresInUse = "snowChainsOrTyresInUse"
    snowTyresInUse = "snowTyresInUse"
    speedLimiterInUse = "speedLimiterInUse"
    studdedTyresInUse = "studdedTyresInUse"
    wheelchairSystem = "wheelchairSystem"
    withoutSnowTyresOrChainsOnBoard = "withoutSnowTyresOrChainsOnBoard"


class VehicleType(Enum):
    """
    Types of vehicle.
    """

    agriculturalVehicle = "agriculturalVehicle"
    ambulance = "ambulance"
    anyVehicle = "anyVehicle"
    articulatedVehicle = "articulatedVehicle"
    bus = "bus"
    car = "car"
    caravan = "caravan"
    coastguardVehicle = "coastguardVehicle"
    diplomaticVehicle = "diplomaticVehicle"
    emergencyServicesVehicle = "emergencyServicesVehicle"
    emergencyAndIncidentSupportVehicle = "emergencyAndIncidentSupportVehicle"
    fireServiceVehicle = "fireServiceVehicle"
    goodsVehicle = "goodsVehicle"
    horseDrawnVehicle = "horseDrawnVehicle"
    heavyGoodsVehicle = "heavyGoodsVehicle"
    lightRailTram = "lightRailTram"
    mopedSmallMotorcycle = "mopedSmallMotorcycle"
    motorcycle = "motorcycle"
    motorVehicle = "motorVehicle"
    other = "other"
    publicServiceVehicle = "publicServiceVehicle"
    pedalCycle = "pedalCycle"
    policeVehicle = "policeVehicle"
    poweredVehicleUsedByDisabledPeople = "poweredVehicleUsedByDisabledPeople"
    schoolBus = "schoolBus"
    soloMotorcycle = "soloMotorcycle"
    taxi = "taxi"
    trackedLayingVehicle = "trackedLayingVehicle"
    vehicleWithTrailer = "vehicleWithTrailer"


class VehicleUsageType(Enum):
    """
    List of vehicle usage types
    """

    access = "access"
    accessToOffStreetPremises = "accessToOffStreetPremises"
    authorisedVehicles = "authorisedVehicles"
    busOperationPurpose = "busOperationPurpose"
    dialARide = "dialARide"
    guidedBuses = "guidedBuses"
    highwayAuthorityPurpose = "highwayAuthorityPurpose"
    localBuses = "localBuses"
    locallyRegisteredPrivateHireVehicle = "locallyRegisteredPrivateHireVehicle"
    military = "military"
    other = "other"
    privateHireVehicle = "privateHireVehicle"
    statutoryUndertakerPurpose = "statutoryUndertakerPurpose"


class WeekInMonthType(Enum):
    """
    Week of month.
    """

    fifthWeek = "fifthWeek"
    firstWeek = "firstWeek"
    fourthWeek = "fourthWeek"
    secondWeek = "secondWeek"
    sixthWeek = "sixthWeek"
    thirdWeek = "thirdWeek"


class WeightType(Enum):
    """
    The meaning of the weight value
    """

    actual = "actual"
    combinedMaximumPermitted = "combinedMaximumPermitted"
    maximumPermitted = "maximumPermitted"
    unladen = "unladen"


class ConditionOperatorType(Enum):
    """
    Logical operators
    """

    and_ = "and"
    or_ = "or"
    xOr = "xOr"


class ChangeableTimePeriodSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition: str = Field(..., min_length=1)
    sourceLocator: str


class SpecialDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intersectWithApplicableDays: bool
    publicEvent: PublicEventType | None = None
    specialDayType: SpecialDayType
    publicHolidayName: str | None = Field(None, min_length=1)


class ConditionalOrderReportingPoints(Enum):
    experimentalAmendment = "experimentalAmendment"
    experimentalMakingPermanent = "experimentalMakingPermanent"
    experimentalNoticeOfMaking = "experimentalNoticeOfMaking"
    experimentalRevocation = "experimentalRevocation"
    permanentAmendment = "permanentAmendment"
    permanentNoticeOfMaking = "permanentNoticeOfMaking"
    permanentRevocation = "permanentRevocation"
    specialEventOrderNoticeOfMaking = "specialEventOrderNoticeOfMaking"


class HhMMSSPattern(RootModel[str]):
    root: str = Field(..., pattern="^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$")


class AccessCondition(BaseModel):
    """
    Object indicating condition controlling access
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    accessConditionType: list[AccessConditionType] = Field(..., min_length=1)
    otherAccessRestriction: str | None = Field(
        None,
        description="Free text description of other access restrictions.",
        min_length=1,
    )


class ActualStartOrStop(BaseModel):
    """
    Object supporting the recording of actual start and stop dates and times
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    eventAt: str = Field(
        ..., description="Indicates the date / time of the related event"
    )
    eventType: EventType


class RoadCondition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    roadType: RoadType


class DriverCondition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    driverCharacteristics: DriverCharacteristicsType


class ExtensionEnumeration(BaseModel):
    """
    User-definition of a new list entry.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    definition: str = Field(..., description="User defined definition.", min_length=1)
    enumeratedList: TargetEnumeratedList = Field(
        ..., description="Enumeration list to extend."
    )
    value: str = Field(..., description="The user-defined value.", min_length=1)


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    lastUpdateDate: str
    uniqueStreetReferenceNumber: list[UniqueStreetReferenceNumber] = Field(
        ..., min_length=1
    )


class GeneralRegulation(BaseModel):
    """
    A list of regulation types
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    regulationType: RegulationType


class LinearGeometry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    diversionType: DiversionType | None = None
    version: int = Field(..., ge=1)
    direction: LinearDirectionType
    lateralPosition: LinearLateralPositionType
    linestring: str = Field(
        ...,
        pattern="^SRID=27700;(MULTILINESTRING ?\\(\\(.*\\)\\)|LINESTRING ?\\(.*\\))",
    )
    representation: LinearType
    externalReference: list[ExternalReference] | None = Field(None, min_length=1)


class MaximumGrossWeightCharacteristic(BaseModel):
    """
    Gross weight characteristic of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    grossVehicleWeight: float = Field(
        ..., description="Metric tonnes, one decimal place", ge=0.0
    )
    typeOfWeight: WeightType


class NonVehicularRoadUserCondition(BaseModel):
    """
    Characteristics about non-vehicular road users
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    nonVehicularRoadUser: NonVehicularRoadUserType


class RecurringTimePeriodOfDayItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endTimeOfPeriod: HhMMSSPattern
    startTimeOfPeriod: HhMMSSPattern


class RecurringDayWeekMonthPeriodItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applicableDay: list[DayType] | None = Field(None, max_length=7, min_length=1)
    applicableDayWithinMonth: list[DayWithinMonth] | None = Field(
        None, max_length=31, min_length=1
    )
    applicableMonth: list[MonthType] | None = Field(None, max_length=12, min_length=1)
    weekInMonth: CalendarWeekInMonthType | None = None
    applicableWeek: WeekInMonthType | None = None
    applicableInstanceOfDayWithinMonth: InstanceOfDayInMonth | None = None


class PointGeometry(BaseModel):
    """
    Point geometry location
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    diversionType: DiversionType | None = None
    externalReference: list[ExternalReference] | None = Field(None, min_length=1)
    point: str = Field(
        ..., pattern="^SRID=27700;(MULTIPOINT ?\\(\\(.*\\)\\)|POINT ?\\(.*\\))"
    )
    representation: PointType = Field(..., description="Nature of the point location.")
    version: int = Field(..., ge=1)


class Polygon(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    diversionType: DiversionType | None = None
    version: int = Field(..., ge=1)
    polygon: str = Field(
        ...,
        pattern="^SRID=27700;(MULTIPOLYGON ?\\(\\(\\(.*\\)\\)\\)|POLYGON ?\\(\\(.*\\)\\))",
    )
    externalReference: list[ExternalReference] | None = Field(None, min_length=1)


class RateLine(BaseModel):
    """
    Rate line within a rate table
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    description: str | None = Field(
        None, description="Free-text description.", min_length=1
    )
    durationEnd: HhMMSSPattern | None = Field(
        None, description="End time for the applicability."
    )
    durationStart: HhMMSSPattern | None = Field(
        None, description="Start time for the applicability."
    )
    incrementPeriod: int | None = Field(
        None, description="Time period for incrementing the rate line charge, minutes."
    )
    maxValue: float | None = Field(
        None,
        description="Maximum monetary amount, two decimal places.",
        gt=0.0,
        multiple_of=0.01,
    )
    minValue: float | None = Field(
        None,
        description="Minimum monetary amount, two decimal places.",
        gt=0.0,
        multiple_of=0.01,
    )
    sequence: int = Field(
        ..., description="Ordered sequence within the rate line collection.", ge=0
    )
    type: RateLineType = Field(..., description="Nature of the rate line.")
    usageCondition: RateUsageConditionsType | None = Field(
        None, description="Conditions on the use of this rate line."
    )
    value: float = Field(
        ...,
        description="Value of the fee, two decimal places.",
        ge=0.0,
        multiple_of=0.01,
    )


class RateLineCollection(BaseModel):
    """
    Group of rate line elements within one rate table.
    """

    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    applicableCurrency: CurrencyType = Field(..., description="The monetary currency.")
    startValidUsagePeriod: str = Field(
        ..., description="Start time for validity."
    )
    endValidUsagePeriod: str | None = Field(
        None, description="End time for validity."
    )
    maxTime: str | None = Field(
        None,
        description="Max session duration (ISO 8601).",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )
    minTime: str | None = Field(
        None,
        description="Min session duration (ISO 8601).",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )
    maxValueCollection: float | None = Field(
        None,
        description="Maximum monetary amount, two decimal places.",
        gt=0.0,
        multiple_of=0.01,
    )
    minValueCollection: float | None = Field(
        None,
        description="Minimum monetary amount, two decimal places.",
        gt=0.0,
        multiple_of=0.01,
    )
    resetTime: HhMMSSPattern | None = Field(None, description="Time that rate resets.")
    sequence: int = Field(
        ..., description="Place in sequence of this rate line collection.", ge=0
    )
    rateLine: list[RateLine] = Field(..., min_length=1)


class RateTable(BaseModel):
    """
    Set of rate charges relating to one or more locations.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: RateType | None = Field(None, description="Type of rate in use.")
    additionalInformation: str | None = Field(
        None, description="URI for supplementary information."
    )
    rateLineCollection: list[RateLineCollection] = Field(..., min_length=1)


class RoadCondition9(BaseModel):
    """
    Characteristics concerning the type of road.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    roadType: RoadType = Field(..., description="Type of road")


class SpeedLimitProfileBased(BaseModel):
    type: SpeedLimitProfileType | None = None


class SpeedLimitValueBased(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mphValue: MphValue
    nature: SpeedLimitNatureType
    type: SpeedLimitValueType


class ValueRange(BaseModel):
    """
    Class defining a measurable quantity and related units.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    class_: ValueRangeClassEnum = Field(..., alias="class")
    unit: UnitOfMeasureEnum
    valueRangeBoundary: list[ValueRangeBoundary] | None = Field(
        None, max_length=2, min_length=0
    )


class ChangeableTimePeriodStart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    startType: ChangeableTimeType
    changeableTimePeriodSource: ChangeableTimePeriodSource | None = None
    specialDay: SpecialDay | None = None


class ChangeableTimePeriodEnd(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endType: ChangeableTimeType
    changeableTimePeriodSource: ChangeableTimePeriodSource | None = None
    specialDay: SpecialDay | None = None


class PermitCondition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class PermitCondition8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    locationRelatedPermit: bool | None = None
    maxDurationOfPermit: int | None = Field(None, ge=1)
    permitIdentifier: str | None = Field(None, min_length=1)
    schemeIdentifier: str | None = Field(None, min_length=1)
    whereToApplyForPermit: str | None = None
    whereToCallForPermit: str | None = Field(None, min_length=1)
    type: PermitType
    maximumAccessDuration: int | None = Field(None, ge=1)
    minimumTimeToNextEntry: int | None = Field(None, ge=1)
    authority: Authority1 | None = None
    permitTypeExtension: ExtensionEnumeration | None = None


class DirectedLinear(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    diversionType: DiversionType | None = None
    version: int = Field(..., ge=1)
    directedLineString: str = Field(
        ...,
        pattern="^SRID=27700;(MULTILINESTRING ?\\(\\(.*\\)\\)|LINESTRING ?\\(.*\\))",
    )
    destination: list[ExternalReference] | None = Field(None, min_length=1)
    intermediateLocation: list[ExternalReference] | None = Field(None, min_length=1)
    origin: list[ExternalReference] | None = Field(None, min_length=1)


class Emissions(BaseModel):
    """
    Emission characteristics of vehicles.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    emissionClassificationEuro: EmissionClassificationEuroType | None = None
    emissionClassificationOther: list[str] | None = Field(
        None, description="Locally defined value(s).", min_length=1
    )
    emissionClassificationEuroTypeExtension: ExtensionEnumeration | None = None
    valueRange: list[ValueRange] | None = Field(None, min_length=0)


class GeometryType1(BaseModel):
    description: str = Field(..., min_length=1)
    type: RegulatedPlaceType
    pointGeometry: PointGeometry
    linearGeometry: LinearGeometry | None = None
    polygon: Polygon | None = None
    directedLinear: DirectedLinear | None = None


class GeometryType2(BaseModel):
    description: str = Field(..., min_length=1)
    type: RegulatedPlaceType
    pointGeometry: PointGeometry | None = None
    linearGeometry: LinearGeometry
    polygon: Polygon | None = None
    directedLinear: DirectedLinear | None = None


class GeometryType3(BaseModel):
    description: str = Field(..., min_length=1)
    type: RegulatedPlaceType
    pointGeometry: PointGeometry | None = None
    linearGeometry: LinearGeometry | None = None
    polygon: Polygon
    directedLinear: DirectedLinear | None = None


class GeometryType4(BaseModel):
    description: str = Field(..., min_length=1)
    type: RegulatedPlaceType
    pointGeometry: PointGeometry | None = None
    linearGeometry: LinearGeometry | None = None
    polygon: Polygon | None = None
    directedLinear: DirectedLinear


class GeometryType(
    RootModel[GeometryType1 | GeometryType2 | GeometryType3 | GeometryType4]
):
    root: GeometryType1 | GeometryType2 | GeometryType3 | GeometryType4


class Period(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endOfPeriod: str | None = None
    startOfPeriod: str | None = None
    periodName: str | None = Field(None, min_length=1)
    recurrents: int | None = None
    recurringPeriod: int | None = None
    recurringTimePeriodOfDay: list[RecurringTimePeriodOfDayItem] | None = Field(
        None, min_length=1
    )
    recurringDayWeekMonthPeriod: list[RecurringDayWeekMonthPeriodItem] | None = Field(
        None, min_length=1
    )
    recurringSpecialDay: list[SpecialDay] | None = Field(None, min_length=1)
    periodStart: ChangeableTimePeriodStart | None = None
    periodEnd: ChangeableTimePeriodEnd | None = None


class RegulatedPlace1(BaseModel):
    """
    Geographical and spatial location subject to a regulation
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assignment: bool | None = Field(
        None, description="Subject to an assignment under s28(1) NRSWA 1991"
    )
    busRoute: bool | None = Field(None, description="Relates to a bus route road")
    bywayType: BywayType | None = Field(None, description="Byway type")
    concession: bool | None = Field(
        None, description="Free text description of the regulated place"
    )
    description: str = Field(
        ..., description="Free text description of the regulated place", min_length=1
    )
    tramcar: bool | None = Field(None, description="Relates to a tramcar/trolley road")
    type: RegulatedPlaceType = Field(..., description="Nature of the regulated place")
    polygon: Polygon
    directedLinear: DirectedLinear | None = None
    linearGeometry: LinearGeometry | None = None
    pointGeometry: PointGeometry | None = None


class RegulatedPlace2(BaseModel):
    """
    Geographical and spatial location subject to a regulation
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assignment: bool | None = Field(
        None, description="Subject to an assignment under s28(1) NRSWA 1991"
    )
    busRoute: bool | None = Field(None, description="Relates to a bus route road")
    bywayType: BywayType | None = Field(None, description="Byway type")
    concession: bool | None = Field(
        None, description="Free text description of the regulated place"
    )
    description: str = Field(
        ..., description="Free text description of the regulated place", min_length=1
    )
    tramcar: bool | None = Field(None, description="Relates to a tramcar/trolley road")
    type: RegulatedPlaceType = Field(..., description="Nature of the regulated place")
    polygon: Polygon | None = None
    directedLinear: DirectedLinear
    linearGeometry: LinearGeometry | None = None
    pointGeometry: PointGeometry | None = None


class RegulatedPlace3(BaseModel):
    """
    Geographical and spatial location subject to a regulation
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assignment: bool | None = Field(
        None, description="Subject to an assignment under s28(1) NRSWA 1991"
    )
    busRoute: bool | None = Field(None, description="Relates to a bus route road")
    bywayType: BywayType | None = Field(None, description="Byway type")
    concession: bool | None = Field(
        None, description="Free text description of the regulated place"
    )
    description: str = Field(
        ..., description="Free text description of the regulated place", min_length=1
    )
    tramcar: bool | None = Field(None, description="Relates to a tramcar/trolley road")
    type: RegulatedPlaceType = Field(..., description="Nature of the regulated place")
    polygon: Polygon | None = None
    directedLinear: DirectedLinear | None = None
    linearGeometry: LinearGeometry
    pointGeometry: PointGeometry | None = None


class RegulatedPlace4(BaseModel):
    """
    Geographical and spatial location subject to a regulation
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    assignment: bool | None = Field(
        None, description="Subject to an assignment under s28(1) NRSWA 1991"
    )
    busRoute: bool | None = Field(None, description="Relates to a bus route road")
    bywayType: BywayType | None = Field(None, description="Byway type")
    concession: bool | None = Field(
        None, description="Free text description of the regulated place"
    )
    description: str = Field(
        ..., description="Free text description of the regulated place", min_length=1
    )
    tramcar: bool | None = Field(None, description="Relates to a tramcar/trolley road")
    type: RegulatedPlaceType = Field(..., description="Nature of the regulated place")
    polygon: Polygon | None = None
    directedLinear: DirectedLinear | None = None
    linearGeometry: LinearGeometry | None = None
    pointGeometry: PointGeometry


class RegulatedPlace(
    RootModel[RegulatedPlace1 | RegulatedPlace2 | RegulatedPlace3 | RegulatedPlace4]
):
    root: RegulatedPlace1 | RegulatedPlace2 | RegulatedPlace3 | RegulatedPlace4 = Field(
        ..., description="Geographical and spatial location subject to a regulation"
    )


class TimeValidity9(BaseModel):
    """
    A continuous or discontinuous period of validity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    end: str | None = Field(None, description="End of time validity.")
    isPlaceholderTro: bool = Field(
        ..., description="Whether the record is a placeholder."
    )
    start: str = Field(..., description="Start of time validity.")
    validPeriod: list[Period] | None = None
    exceptionPeriod: list[Period] | None = None
    maxStayNoReturn: MaxStayNoReturn | None = None


class VehicleCharacteristics(BaseModel):
    """
    The characteristics of a vehicle.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    fuelType: list[FuelType] | None = Field(None, min_length=1)
    fuelTypeExtension: ExtensionEnumeration | None = None
    loadType: PayloadType | None = None
    payloadTypeExtension: ExtensionEnumeration | None = None
    vehicleEquipment: VehicleEquipmentType | None = None
    vehicleEquipmentTypeExtension: ExtensionEnumeration | None = None
    vehicleType: VehicleType | None = None
    vehicleTypeExtension: ExtensionEnumeration | None = None
    vehicleUsage: VehicleUsageType | None = None
    yearOfFirstRegistration: int | None = Field(
        None, description="Year of first registration", ge=1
    )
    maximumGrossWeightCharacteristic: MaximumGrossWeightCharacteristic | None = None
    maximumHeightCharacteristic: MaximumHeightCharacteristic | None = None
    maximumLengthCharacteristic: MaximumLengthCharacteristic | None = None
    maximumWidthCharacteristic: MaximumWidthCharacteristic | None = None
    heaviestAxleWeightCharacteristic: HeaviestAxleWeightCharacteristic | None = None
    numberOfAxlesCharacteristic: list[NumberOfAxlesCharacteristic] | None = Field(
        None, max_length=2, min_length=0
    )
    emissions: Emissions | None = None
    vehicleUsageTypeExtension: ExtensionEnumeration | None = None
    electricChargingCharacteristic: ElectricChargingCharacteristic | None = None


class TimeValidity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: str | None = None
    isPlaceholderTro: bool
    start: str
    validPeriod: list[Period] | None = None
    exceptionPeriod: list[Period] | None = None
    maxStayNoReturn: MaxStayNoReturn | None = None


class Condition1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition | None = None


class Condition2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition1 | None = None


class Condition3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition2 | None = None


class Condition4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition3 | None = None


class Condition5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition4 | None = None


class Condition6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition5 | None = None


class Condition7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition
    permitCondition: PermitCondition6 | None = None


class Condition8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics | None = None
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition7


class Condition9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    negate: bool | None = None
    operator: ConditionOperatorType | None = None
    rateTable: RateTable | None = None
    vehicleCharacteristics: VehicleCharacteristics
    roadCondition: RoadCondition | None = None
    otherCondition: OtherCondition | None = None
    occupantCondition: OccupantCondition | None = None
    driverCondition: DriverCondition | None = None
    accessCondition: AccessCondition1 | None = None
    timeValidity: TimeValidity | None = None
    nonVehicularRoadUserCondition: NonVehicularRoadUserCondition | None = None
    permitCondition: PermitCondition8 | None = None


class Condition(
    RootModel[
        Condition1
        | Condition2
        | Condition3
        | Condition4
        | Condition5
        | Condition6
        | Condition7
        | Condition8
        | Condition9
    ]
):
    root: (
        Condition1
        | Condition2
        | Condition3
        | Condition4
        | Condition5
        | Condition6
        | Condition7
        | Condition8
        | Condition9
    )


class Model1(BaseModel):
    """
    DTRO v3.5.1 Data Specification JSON schema
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source
    consultation: Consultation | None = None


class Model2(BaseModel):
    """
    DTRO v3.5.1 Data Specification JSON schema
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source | None = None
    consultation: Consultation


class Conditions1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operator: str | None = None
    condition: list[Condition] | None = Field(None, min_length=1)
    conditionSet: ConditionSet | None = None


class ConditionSetItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operator: ConditionOperatorType | None = None
    conditionSet: ConditionSet | None = None
    conditions: Conditions | None = None
    condition: list[Condition] | None = Field(None, max_length=1, min_length=1)


class Consultation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    consultationName: str = Field(
        ...,
        description="Free text descriptive name for the consultation.",
        min_length=1,
    )
    endOfConsultation: str = Field(
        ..., description="Time and date of the end of the consultation period"
    )
    howToComment: str | None = Field(
        None, description="How to comment on the proposal.", min_length=1
    )
    localReference: str | None = Field(
        None, description="Free text reference identifier.", min_length=1
    )
    pointOfContactAddress: str | None = Field(
        None, description="Postal or office address.", min_length=1
    )
    pointOfContactEmail: str | None = Field(None, description="Email address.")
    startOfConsultation: str | None = Field(
        None, description="Start of the consultation period"
    )
    statementOfReason: str = Field(
        ..., description="Statement of reason.", min_length=1
    )
    urlAdditionalInformation: str | None = Field(
        None, description="URL for further information."
    )
    source: list[Source] = Field(..., min_length=1)


class Provision(BaseModel):
    """
    Characteristics of a traffic regulation measure specified Provision.
    """

    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    actionType: ProvisionActionType
    comingIntoForceDate: str | None = Field(
        None, description="Date the provision comes into force", min_length=1
    )
    expectedOccupancyDuration: str | None = Field(
        None,
        description="Expected duration of occupancy",
        pattern="^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+(\\.\\d+)?S)?)?$",
    )
    orderReportingPoint: OrderReportingPointType
    provisionDescription: str = Field(..., min_length=1)
    reference: str = Field(..., min_length=1)
    actualStartOrStop: list[ActualStartOrStop] | None = Field(None, min_length=1)
    experimentalCessation: ExperimentalCessation | None = None
    experimentalVariation: ExperimentalVariation | None = None
    regulatedPlace: list[RegulatedPlace] = Field(..., min_length=1)
    regulation: Regulation


class RegulationItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    isDynamic: bool = Field(..., description="Indicates if the regulation is dynamic")
    timeZone: str = Field(..., description="IANA time-zone", min_length=1)
    conditionSet: ConditionSet | None = None
    condition: list[Condition] | None = Field(None, max_length=1, min_length=1)
    generalRegulation: GeneralRegulation | None = None
    offListRegulation: OffListRegulation | None = None
    speedLimitValueBased: SpeedLimitValueBased | None = None
    speedLimitProfileBased: SpeedLimitProfileBased | None = None
    temporaryProvision: list[TemporaryProvision] | None = Field(None, min_length=0)


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actionType: SourceActionType
    comingIntoForceDate: str | None = Field(
        None, description="Date the TRO comes into force", min_length=1
    )
    currentTraOwner: int = Field(..., ge=1)
    madeDate: str | None = Field(
        None, description="Date the TRO is made", min_length=1
    )
    reference: str = Field(..., min_length=1)
    section: str = Field(
        ..., description="Reference to the section of the TRO", min_length=1
    )
    statementDescription: str = Field(
        ...,
        description="Statement of the overall nature of the restriction",
        min_length=1,
    )
    traAffected: list[TraAffectedItem] = Field(
        ..., description="TRAs affected by this TRO", min_length=1
    )
    traCreator: int = Field(
        ..., description="Highway Regulation Authority (SWA-like code)", ge=1
    )
    troName: str = Field(
        ..., description="Published title of the Traffic Regulation Order", min_length=1
    )
    provision: list[Provision] = Field(..., min_length=1)


class Model(RootModel[Model1 | Model2]):
    root: Model1 | Model2 = Field(
        ..., description="DTRO v3.5.1 Data Specification JSON schema"
    )


class Conditions(RootModel[list[Condition | Conditions1]]):
    root: list[Condition | Conditions1] = Field(..., min_length=1)


class ConditionSet(RootModel[list[ConditionSetItem]]):
    root: list[ConditionSetItem]


class Regulation(RootModel[list[RegulationItem]]):
    """
    Characteristics of a regulation
    """

    root: list[RegulationItem] = Field(
        ..., description="Characteristics of a regulation", max_length=1, min_length=1
    )


Model1.model_rebuild()
Model2.model_rebuild()
Conditions1.model_rebuild()
ConditionSetItem.model_rebuild()
Consultation.model_rebuild()
Provision.model_rebuild()
RegulationItem.model_rebuild()
